In [2]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
import seaborn as sns
import warnings

In [12]:
#Wimbledon point-by-point
pts_2011_wimbledon = pd.read_csv('./data/2011-wimbledon-points.csv')
pts_2012_wimbledon = pd.read_csv('./data/2012-wimbledon-points.csv')
pts_2013_wimbledon = pd.read_csv('./data/2013-wimbledon-points.csv')
pts_2014_wimbledon = pd.read_csv('./data/2014-wimbledon-points.csv')
pts_2015_wimbledon = pd.read_csv('./data/2015-wimbledon-points.csv')
pts_2016_wimbledon = pd.read_csv('./data/2016-wimbledon-points.csv')
pts_2017_wimbledon = pd.read_csv('./data/2017-wimbledon-points.csv')
pts_2018_wimbledon = pd.read_csv('./data/2018-wimbledon-points.csv')
pts_2019_wimbledon = pd.read_csv('./data/2019-wimbledon-points.csv')

/Users/sashaepelbaum/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
#Australien Open point-by-point
pts_2011_ausopen = pd.read_csv('./data/2011-ausopen-points.csv')
pts_2012_ausopen = pd.read_csv('./data/2012-ausopen-points.csv')
pts_2013_ausopen = pd.read_csv('./data/2013-ausopen-points.csv')
pts_2014_ausopen = pd.read_csv('./data/2014-ausopen-points.csv')
pts_2015_ausopen = pd.read_csv('./data/2015-ausopen-points.csv')
pts_2016_ausopen = pd.read_csv('./data/2016-ausopen-points.csv')
pts_2017_ausopen = pd.read_csv('./data/2017-ausopen-points.csv')

In [14]:
#US Open point-by-point
pts_2011_usopen = pd.read_csv('./data/2011-usopen-points.csv')
pts_2012_usopen = pd.read_csv('./data/2012-usopen-points.csv')
pts_2013_usopen = pd.read_csv('./data/2013-usopen-points.csv')
pts_2014_usopen = pd.read_csv('./data/2014-usopen-points.csv')
pts_2015_usopen = pd.read_csv('./data/2015-usopen-points.csv')
pts_2016_usopen = pd.read_csv('./data/2016-usopen-points.csv')
pts_2017_usopen = pd.read_csv('./data/2017-usopen-points.csv')
pts_2018_usopen = pd.read_csv('./data/2018-usopen-points.csv')
pts_2019_usopen = pd.read_csv('./data/2019-usopen-points.csv')

In [15]:
#French Open point-by-point
pts_2011_frenchopen = pd.read_csv('./data/2011-frenchopen-points.csv')
pts_2012_frenchopen = pd.read_csv('./data/2012-frenchopen-points.csv')
pts_2013_frenchopen = pd.read_csv('./data/2013-frenchopen-points.csv')
pts_2014_frenchopen = pd.read_csv('./data/2014-frenchopen-points.csv')
pts_2015_frenchopen = pd.read_csv('./data/2015-frenchopen-points.csv')
pts_2016_frenchopen = pd.read_csv('./data/2016-frenchopen-points.csv')
pts_2017_frenchopen = pd.read_csv('./data/2017-frenchopen-points.csv')

In [19]:
list_of_dfs = [
    pts_2011_wimbledon,
    pts_2012_wimbledon,
    pts_2013_wimbledon,
    pts_2014_wimbledon,
    pts_2015_wimbledon,
    pts_2016_wimbledon,
    pts_2017_wimbledon,
    pts_2018_wimbledon,
    pts_2019_wimbledon,
    pts_2011_ausopen,
    pts_2012_ausopen,
    pts_2013_ausopen,
    pts_2014_ausopen,
    pts_2015_ausopen,
    pts_2016_ausopen,
    pts_2017_ausopen,
    pts_2011_usopen,
    pts_2012_usopen,
    pts_2013_usopen,
    pts_2014_usopen,
    pts_2015_usopen,
    pts_2016_usopen,
    pts_2017_usopen,
    pts_2018_usopen,
    pts_2019_usopen,
    pts_2011_frenchopen,
    pts_2012_frenchopen,
    pts_2013_frenchopen,
    pts_2014_frenchopen,
    pts_2015_frenchopen,
    pts_2016_frenchopen,
    pts_2017_frenchopen
]

In [32]:
for df in list_of_dfs:
    df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21368 entries, 0 to 21367
Data columns (total 55 columns):
match_id              21368 non-null object
ElapsedTime           21368 non-null object
SetNo                 21368 non-null int64
P1GamesWon            21368 non-null int64
P2GamesWon            21368 non-null int64
SetWinner             21368 non-null int64
GameNo                21368 non-null int64
GameWinner            21368 non-null int64
PointNumber           21368 non-null int64
PointWinner           21368 non-null int64
PointServer           21368 non-null int64
Speed_KMH             21368 non-null int64
Rally                 21368 non-null int64
P1Score               21368 non-null object
P2Score               21368 non-null object
P1Momentum            21368 non-null int64
P2Momentum            21368 non-null int64
P1PointsWon           21368 non-null int64
P2PointsWon           21368 non-null int64
P1Ace                 21368 non-null int64
P2Ace                 21368 non-null int64
P1Winner              21368 non-null int64
P2Winner              21368 non-null int64
P1DoubleFault         21368 non-null int64
P2DoubleFault         21368 non-null int64
P1UnfErr              21368 non-null int64
P2UnfErr              21368 non-null int64
P1NetPoint            21368 non-null int64
P2NetPoint            21368 non-null int64
P1NetPointWon         21368 non-null int64
P2NetPointWon         21368 non-null int64
P1BreakPoint          21368 non-null int64
P2BreakPoint          21368 non-null int64
P1BreakPointWon       21368 non-null int64
P2BreakPointWon       21368 non-null int64
P1FirstSrvIn          21368 non-null int64
P2FirstSrvIn          21368 non-null int64
P1FirstSrvWon         21368 non-null int64
P2FirstSrvWon         21368 non-null int64
P1SecondSrvIn         21368 non-null int64
P2SecondSrvIn         21368 non-null int64
P1SecondSrvWon        21368 non-null int64
P2SecondSrvWon        21368 non-null int64
P1ForcedError         21368 non-null int64
P2ForcedError         21368 non-null int64
History               21368 non-null int64
Speed_MPH             21368 non-null int64
P1BreakPointMissed    21368 non-null int64
P2BreakPointMissed    21368 non-null int64
ServeIndicator        21368 non-null int64
Serve_Direction       21368 non-null int64
Winner_FH             21368 non-null int64
Winner_BH             21368 non-null int64
P1TurningPoint        21368 non-null int64
P2TurningPoint        21368 non-null int64
dtypes: int64(51), object(4)
memory usage: 9.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25920 entries, 0 to 25919
Data columns (total 56 columns):
match_id              25920 non-null object
ElapsedTime           25920 non-null object
SetNo                 25920 non-null int64
P1GamesWon            25920 non-null int64
P2GamesWon            25920 non-null int64
SetWinner             25920 non-null int64
GameNo                25920 non-null int64
GameWinner            25920 non-null int64
PointNumber           25920 non-null int64
PointWinner           25920 non-null int64
PointServer           25920 non-null int64
Speed_KMH             25920 non-null int64
Rally                 0 non-null float64
P1Score               25920 non-null object
P2Score               25920 non-null object
P1Momentum            25920 non-null int64
P2Momentum            25920 non-null int64
P1PointsWon           25920 non-null int64
P2PointsWon           25920 non-null int64
P1Ace                 25920 non-null int64
P2Ace                 25920 non-null int64
P1Winner              25920 non-null int64
P2Winner              25920 non-null int64
P1DoubleFault         25920 non-null int64
P2DoubleFault         25920 non-null int64
P1UnfErr              25920 non-null int64
P2UnfErr              25920 non-null int64
P1NetPoint            25920 non-null int64
P2NetPoint            25920 non-null int64
P1NetPointWon         25920 non-null int64
P2NetPointWon         25920 non-null int64
P1BreakPoint          25920 non-null int64
P2BreakPoint          25920 non-null int64
P1BreakPointWon       25920 non-null int64
P2BreakPointWon       25920 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               25920 non-null int64
Speed_MPH             25920 non-null int64
P1BreakPointMissed    25920 non-null int64
P2BreakPointMissed    25920 non-null int64
ServeIndicator        25920 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1269 non-null object
P2TurningPoint        1266 non-null object
dtypes: float64(15), int64(35), object(6)
memory usage: 11.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25691 entries, 0 to 25690
Data columns (total 56 columns):
match_id              25691 non-null object
ElapsedTime           25691 non-null object
SetNo                 25691 non-null int64
P1GamesWon            25691 non-null int64
P2GamesWon            25691 non-null int64
SetWinner             25691 non-null int64
GameNo                25691 non-null int64
GameWinner            25691 non-null int64
PointNumber           25691 non-null int64
PointWinner           25691 non-null int64
PointServer           25691 non-null int64
Speed_KMH             25691 non-null int64
Rally                 0 non-null float64
P1Score               25691 non-null object
P2Score               25691 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           25691 non-null int64
P2PointsWon           25691 non-null int64
P1Ace                 25691 non-null int64
P2Ace                 25691 non-null int64
P1Winner              25691 non-null int64
P2Winner              25691 non-null int64
P1DoubleFault         25691 non-null int64
P2DoubleFault         25691 non-null int64
P1UnfErr              25691 non-null int64
P2UnfErr              25691 non-null int64
P1NetPoint            25691 non-null int64
P2NetPoint            25691 non-null int64
P1NetPointWon         25691 non-null int64
P2NetPointWon         25691 non-null int64
P1BreakPoint          25691 non-null int64
P2BreakPoint          25691 non-null int64
P1BreakPointWon       25691 non-null int64
P2BreakPointWon       25691 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               25691 non-null int64
Speed_MPH             25691 non-null int64
P1BreakPointMissed    25691 non-null int64
P2BreakPointMissed    25691 non-null int64
ServeIndicator        25691 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
dtypes: float64(19), int64(33), object(4)
memory usage: 11.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47619 entries, 0 to 47618
Data columns (total 59 columns):
match_id              47619 non-null object
ElapsedTime           47619 non-null object
SetNo                 47619 non-null int64
P1GamesWon            47619 non-null int64
P2GamesWon            47619 non-null int64
SetWinner             47619 non-null int64
GameNo                47619 non-null int64
GameWinner            47619 non-null int64
PointNumber           47619 non-null int64
PointWinner           47619 non-null int64
PointServer           47619 non-null int64
Speed_KMH             47619 non-null int64
Rally                 0 non-null float64
P1Score               47619 non-null object
P2Score               47619 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           47619 non-null int64
P2PointsWon           47619 non-null int64
P1Ace                 47619 non-null int64
P2Ace                 47619 non-null int64
P1Winner              47619 non-null int64
P2Winner              47619 non-null int64
P1DoubleFault         47619 non-null int64
P2DoubleFault         47619 non-null int64
P1UnfErr              47619 non-null int64
P2UnfErr              47619 non-null int64
P1NetPoint            47619 non-null int64
P2NetPoint            47619 non-null int64
P1NetPointWon         47619 non-null int64
P2NetPointWon         47619 non-null int64
P1BreakPoint          47619 non-null int64
P2BreakPoint          47619 non-null int64
P1BreakPointWon       47619 non-null int64
P2BreakPointWon       47619 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               47366 non-null float64
Speed_MPH             47619 non-null int64
P1BreakPointMissed    47619 non-null int64
P2BreakPointMissed    47619 non-null int64
ServeIndicator        47619 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           47619 non-null int64
WinnerType            47619 non-null object
WinnerShotType        47619 non-null object
dtypes: float64(20), int64(33), object(6)
memory usage: 21.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46819 entries, 0 to 46818
Data columns (total 61 columns):
match_id              46819 non-null object
ElapsedTime           46819 non-null object
SetNo                 46814 non-null float64
P1GamesWon            46814 non-null float64
P2GamesWon            46814 non-null float64
SetWinner             46819 non-null int64
GameNo                46814 non-null float64
GameWinner            46819 non-null int64
PointNumber           46819 non-null int64
PointWinner           46814 non-null float64
PointServer           46814 non-null float64
Speed_KMH             46814 non-null float64
Rally                 0 non-null float64
P1Score               46814 non-null object
P2Score               46814 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           46814 non-null float64
P2PointsWon           46814 non-null float64
P1Ace                 46819 non-null int64
P2Ace                 46819 non-null int64
P1Winner              46819 non-null int64
P2Winner              46819 non-null int64
P1DoubleFault         46819 non-null int64
P2DoubleFault         46819 non-null int64
P1UnfErr              46819 non-null int64
P2UnfErr              46819 non-null int64
P1NetPoint            46819 non-null int64
P2NetPoint            46819 non-null int64
P1NetPointWon         46819 non-null int64
P2NetPointWon         46819 non-null int64
P1BreakPoint          46819 non-null int64
P2BreakPoint          46819 non-null int64
P1BreakPointWon       46819 non-null int64
P2BreakPointWon       46819 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               46562 non-null float64
Speed_MPH             46814 non-null float64
P1BreakPointMissed    46819 non-null int64
P2BreakPointMissed    46819 non-null int64
ServeIndicator        46819 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           46814 non-null float64
WinnerType            46819 non-null object
WinnerShotType        46819 non-null object
P1DistanceRun         46819 non-null float64
P2DistanceRun         46819 non-null float64
dtypes: float64(33), int64(22), object(6)
memory usage: 21.8+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29102 entries, 0 to 29101
Data columns (total 65 columns):
match_id              29102 non-null object
ElapsedTime           29102 non-null object
SetNo                 29102 non-null int64
P1GamesWon            29102 non-null int64
P2GamesWon            29102 non-null int64
SetWinner             29102 non-null int64
GameNo                29102 non-null int64
GameWinner            29102 non-null int64
PointNumber           29102 non-null int64
PointWinner           29102 non-null int64
PointServer           29102 non-null int64
Speed_KMH             29102 non-null int64
Rally                 0 non-null float64
P1Score               29102 non-null object
P2Score               29102 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           29102 non-null int64
P2PointsWon           29102 non-null int64
P1Ace                 29102 non-null int64
P2Ace                 29102 non-null int64
P1Winner              29102 non-null int64
P2Winner              29102 non-null int64
P1DoubleFault         29102 non-null int64
P2DoubleFault         29102 non-null int64
P1UnfErr              29102 non-null int64
P2UnfErr              29102 non-null int64
P1NetPoint            29102 non-null int64
P2NetPoint            29102 non-null int64
P1NetPointWon         29102 non-null int64
P2NetPointWon         29102 non-null int64
P1BreakPoint          29102 non-null int64
P2BreakPoint          29102 non-null int64
P1BreakPointWon       29102 non-null int64
P2BreakPointWon       29102 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               28976 non-null float64
Speed_MPH             29102 non-null int64
P1BreakPointMissed    29102 non-null int64
P2BreakPointMissed    29102 non-null int64
ServeIndicator        29102 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           29101 non-null float64
WinnerType            29102 non-null object
WinnerShotType        29102 non-null object
P1DistanceRun         29102 non-null float64
P2DistanceRun         29102 non-null float64
RallyCount            29102 non-null int64
ServeWidth            13932 non-null object
ServeDepth            13932 non-null object
ReturnDepth           10508 non-null object
dtypes: float64(23), int64(33), object(9)
memory usage: 14.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45774 entries, 0 to 45773
Data columns (total 65 columns):
match_id              45774 non-null object
ElapsedTime           45774 non-null object
SetNo                 45774 non-null int64
P1GamesWon            45774 non-null int64
P2GamesWon            45774 non-null int64
SetWinner             45774 non-null int64
GameNo                45774 non-null int64
GameWinner            45774 non-null int64
PointNumber           45774 non-null int64
PointWinner           45774 non-null int64
PointServer           45774 non-null int64
Speed_KMH             45774 non-null int64
Rally                 0 non-null float64
P1Score               45774 non-null object
P2Score               45774 non-null object
P1Momentum            45774 non-null int64
P2Momentum            45774 non-null int64
P1PointsWon           45774 non-null int64
P2PointsWon           45774 non-null int64
P1Ace                 45774 non-null int64
P2Ace                 45774 non-null int64
P1Winner              45774 non-null int64
P2Winner              45774 non-null int64
P1DoubleFault         45774 non-null int64
P2DoubleFault         45774 non-null int64
P1UnfErr              45774 non-null int64
P2UnfErr              45774 non-null int64
P1NetPoint            45774 non-null int64
P2NetPoint            45774 non-null int64
P1NetPointWon         45774 non-null int64
P2NetPointWon         45774 non-null int64
P1BreakPoint          45774 non-null int64
P2BreakPoint          45774 non-null int64
P1BreakPointWon       45774 non-null int64
P2BreakPointWon       45774 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               45520 non-null float64
Speed_MPH             45774 non-null int64
P1BreakPointMissed    45774 non-null int64
P2BreakPointMissed    45774 non-null int64
ServeIndicator        45774 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           45773 non-null float64
WinnerType            45774 non-null object
WinnerShotType        45774 non-null object
P1DistanceRun         45774 non-null float64
P2DistanceRun         45774 non-null float64
RallyCount            45774 non-null int64
ServeWidth            26114 non-null object
ServeDepth            26114 non-null object
ReturnDepth           20484 non-null object
dtypes: float64(21), int64(35), object(9)
memory usage: 22.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49281 entries, 0 to 49280
Data columns (total 65 columns):
match_id              49281 non-null object
ElapsedTime           49281 non-null object
SetNo                 49281 non-null int64
P1GamesWon            49281 non-null int64
P2GamesWon            49281 non-null int64
SetWinner             49281 non-null int64
GameNo                49281 non-null int64
GameWinner            49281 non-null int64
PointNumber           49281 non-null object
PointWinner           49281 non-null int64
PointServer           49281 non-null int64
Speed_KMH             49281 non-null int64
Rally                 0 non-null float64
P1Score               49281 non-null object
P2Score               49281 non-null object
P1Momentum            49281 non-null int64
P2Momentum            49281 non-null int64
P1PointsWon           49281 non-null int64
P2PointsWon           49281 non-null int64
P1Ace                 49281 non-null int64
P2Ace                 49281 non-null int64
P1Winner              49281 non-null int64
P2Winner              49281 non-null int64
P1DoubleFault         49281 non-null int64
P2DoubleFault         49281 non-null int64
P1UnfErr              49281 non-null int64
P2UnfErr              49281 non-null int64
P1NetPoint            49281 non-null int64
P2NetPoint            49281 non-null int64
P1NetPointWon         49281 non-null int64
P2NetPointWon         49281 non-null int64
P1BreakPoint          49281 non-null int64
P2BreakPoint          49281 non-null int64
P1BreakPointWon       49281 non-null int64
P2BreakPointWon       49281 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               48760 non-null float64
Speed_MPH             49281 non-null int64
P1BreakPointMissed    49281 non-null int64
P2BreakPointMissed    49281 non-null int64
ServeIndicator        49281 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           49281 non-null int64
WinnerType            49281 non-null object
WinnerShotType        49281 non-null object
P1DistanceRun         49281 non-null float64
P2DistanceRun         49281 non-null float64
RallyCount            49281 non-null int64
ServeWidth            27108 non-null object
ServeDepth            27108 non-null object
ReturnDepth           20996 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 24.4+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47045 entries, 0 to 47044
Data columns (total 65 columns):
match_id              47045 non-null object
ElapsedTime           47045 non-null object
SetNo                 47045 non-null int64
P1GamesWon            47045 non-null int64
P2GamesWon            47045 non-null int64
SetWinner             47045 non-null int64
GameNo                47045 non-null int64
GameWinner            47045 non-null int64
PointNumber           47045 non-null object
PointWinner           47045 non-null int64
PointServer           47045 non-null int64
Speed_KMH             47045 non-null int64
Rally                 0 non-null float64
P1Score               47045 non-null object
P2Score               47045 non-null object
P1Momentum            47045 non-null int64
P2Momentum            47045 non-null int64
P1PointsWon           47045 non-null int64
P2PointsWon           47045 non-null int64
P1Ace                 47045 non-null int64
P2Ace                 47045 non-null int64
P1Winner              47045 non-null int64
P2Winner              47045 non-null int64
P1DoubleFault         47045 non-null int64
P2DoubleFault         47045 non-null int64
P1UnfErr              47045 non-null int64
P2UnfErr              47045 non-null int64
P1NetPoint            47045 non-null int64
P2NetPoint            47045 non-null int64
P1NetPointWon         47045 non-null int64
P2NetPointWon         47045 non-null int64
P1BreakPoint          47045 non-null int64
P2BreakPoint          47045 non-null int64
P1BreakPointWon       47045 non-null int64
P2BreakPointWon       47045 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               46537 non-null float64
Speed_MPH             47045 non-null int64
P1BreakPointMissed    47045 non-null int64
P2BreakPointMissed    47045 non-null int64
ServeIndicator        47045 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           47045 non-null int64
WinnerType            47045 non-null object
WinnerShotType        47045 non-null object
P1DistanceRun         47045 non-null float64
P2DistanceRun         47045 non-null float64
RallyCount            47045 non-null int64
ServeWidth            36057 non-null object
ServeDepth            36057 non-null object
ReturnDepth           28897 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 23.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31523 entries, 0 to 31522
Data columns (total 52 columns):
match_id              31523 non-null object
ElapsedTime           31523 non-null object
SetNo                 31522 non-null float64
P1GamesWon            31522 non-null float64
P2GamesWon            31522 non-null float64
SetWinner             31523 non-null int64
GameNo                31522 non-null float64
GameWinner            31523 non-null int64
PointNumber           31523 non-null int64
PointWinner           31522 non-null float64
PointServer           31522 non-null float64
Speed_KMH             31522 non-null float64
Rally                 31522 non-null float64
P1Score               31522 non-null object
P2Score               31522 non-null object
P1Momentum            31523 non-null int64
P2Momentum            31523 non-null int64
P1PointsWon           31522 non-null float64
P2PointsWon           31522 non-null float64
P1Ace                 31522 non-null float64
P2Ace                 31522 non-null float64
P1Winner              31522 non-null float64
P2Winner              31522 non-null float64
P1DoubleFault         31522 non-null float64
P2DoubleFault         31522 non-null float64
P1UnfErr              31522 non-null float64
P2UnfErr              31522 non-null float64
P1NetPoint            31523 non-null int64
P2NetPoint            31523 non-null int64
P1NetPointWon         31523 non-null int64
P2NetPointWon         31523 non-null int64
P1BreakPoint          31523 non-null int64
P2BreakPoint          31523 non-null int64
P1BreakPointWon       31523 non-null int64
P2BreakPointWon       31523 non-null int64
P1FirstSrvIn          31522 non-null float64
P2FirstSrvIn          31522 non-null float64
P1FirstSrvWon         31522 non-null float64
P2FirstSrvWon         31522 non-null float64
P1SecondSrvIn         31522 non-null float64
P2SecondSrvIn         31522 non-null float64
P1SecondSrvWon        31522 non-null float64
P2SecondSrvWon        31522 non-null float64
P1ForcedError         31522 non-null float64
P2ForcedError         31522 non-null float64
History               31522 non-null float64
Speed_MPH             31522 non-null float64
P1BreakPointMissed    31523 non-null int64
P2BreakPointMissed    31523 non-null int64
ServeIndicator        31523 non-null int64
P1TurningPoint        31523 non-null int64
P2TurningPoint        31523 non-null int64
dtypes: float64(30), int64(18), object(4)
memory usage: 12.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29001 entries, 0 to 29000
Data columns (total 56 columns):
match_id              29001 non-null object
ElapsedTime           29001 non-null object
SetNo                 29001 non-null int64
P1GamesWon            29001 non-null int64
P2GamesWon            29001 non-null int64
SetWinner             29001 non-null int64
GameNo                29001 non-null int64
GameWinner            29001 non-null int64
PointNumber           29001 non-null int64
PointWinner           29001 non-null int64
PointServer           29001 non-null int64
Speed_KMH             29001 non-null int64
Rally                 0 non-null float64
P1Score               29001 non-null object
P2Score               29001 non-null object
P1Momentum            29001 non-null int64
P2Momentum            29001 non-null int64
P1PointsWon           29001 non-null int64
P2PointsWon           29001 non-null int64
P1Ace                 29001 non-null int64
P2Ace                 29001 non-null int64
P1Winner              29001 non-null int64
P2Winner              29001 non-null int64
P1DoubleFault         29001 non-null int64
P2DoubleFault         29001 non-null int64
P1UnfErr              29001 non-null int64
P2UnfErr              29001 non-null int64
P1NetPoint            29001 non-null int64
P2NetPoint            29001 non-null int64
P1NetPointWon         29001 non-null int64
P2NetPointWon         29001 non-null int64
P1BreakPoint          29001 non-null int64
P2BreakPoint          29001 non-null int64
P1BreakPointWon       29001 non-null int64
P2BreakPointWon       29001 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               29001 non-null int64
Speed_MPH             29001 non-null int64
P1BreakPointMissed    29001 non-null int64
P2BreakPointMissed    29001 non-null int64
ServeIndicator        29001 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1478 non-null object
P2TurningPoint        1477 non-null object
dtypes: float64(15), int64(35), object(6)
memory usage: 12.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31688 entries, 0 to 31687
Data columns (total 56 columns):
match_id              31688 non-null object
ElapsedTime           31688 non-null object
SetNo                 31688 non-null int64
P1GamesWon            31688 non-null int64
P2GamesWon            31688 non-null int64
SetWinner             31688 non-null int64
GameNo                31688 non-null int64
GameWinner            31688 non-null int64
PointNumber           31688 non-null int64
PointWinner           31688 non-null int64
PointServer           31688 non-null int64
Speed_KMH             31688 non-null int64
Rally                 0 non-null float64
P1Score               31688 non-null object
P2Score               31688 non-null object
P1Momentum            31688 non-null int64
P2Momentum            31688 non-null int64
P1PointsWon           31688 non-null int64
P2PointsWon           31688 non-null int64
P1Ace                 31688 non-null int64
P2Ace                 31688 non-null int64
P1Winner              31688 non-null int64
P2Winner              31688 non-null int64
P1DoubleFault         31688 non-null int64
P2DoubleFault         31688 non-null int64
P1UnfErr              31688 non-null int64
P2UnfErr              31688 non-null int64
P1NetPoint            31688 non-null int64
P2NetPoint            31688 non-null int64
P1NetPointWon         31688 non-null int64
P2NetPointWon         31688 non-null int64
P1BreakPoint          31688 non-null int64
P2BreakPoint          31688 non-null int64
P1BreakPointWon       31688 non-null int64
P2BreakPointWon       31688 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               31688 non-null int64
Speed_MPH             31688 non-null int64
P1BreakPointMissed    31688 non-null int64
P2BreakPointMissed    31688 non-null int64
ServeIndicator        31688 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1572 non-null object
P2TurningPoint        1572 non-null object
dtypes: float64(15), int64(35), object(6)
memory usage: 13.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27659 entries, 0 to 27658
Data columns (total 59 columns):
match_id              27659 non-null object
ElapsedTime           27659 non-null object
SetNo                 27659 non-null int64
P1GamesWon            27659 non-null int64
P2GamesWon            27659 non-null int64
SetWinner             27659 non-null int64
GameNo                27659 non-null int64
GameWinner            27659 non-null int64
PointNumber           27659 non-null int64
PointWinner           27659 non-null int64
PointServer           27659 non-null int64
Speed_KMH             27659 non-null int64
Rally                 0 non-null float64
P1Score               27659 non-null object
P2Score               27659 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           27659 non-null int64
P2PointsWon           27659 non-null int64
P1Ace                 27659 non-null int64
P2Ace                 27659 non-null int64
P1Winner              27659 non-null int64
P2Winner              27659 non-null int64
P1DoubleFault         27659 non-null int64
P2DoubleFault         27659 non-null int64
P1UnfErr              27659 non-null int64
P2UnfErr              27659 non-null int64
P1NetPoint            27659 non-null int64
P2NetPoint            27659 non-null int64
P1NetPointWon         27659 non-null int64
P2NetPointWon         27659 non-null int64
P1BreakPoint          27659 non-null int64
P2BreakPoint          27659 non-null int64
P1BreakPointWon       27659 non-null int64
P2BreakPointWon       27659 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               27659 non-null int64
Speed_MPH             27659 non-null int64
P1BreakPointMissed    27659 non-null int64
P2BreakPointMissed    27659 non-null int64
ServeIndicator        27659 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           0 non-null float64
WinnerType            0 non-null float64
WinnerShotType        0 non-null float64
dtypes: float64(22), int64(33), object(4)
memory usage: 12.5+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38309 entries, 0 to 38308
Data columns (total 59 columns):
match_id              38309 non-null object
ElapsedTime           38309 non-null object
SetNo                 38308 non-null float64
P1GamesWon            38308 non-null float64
P2GamesWon            38308 non-null float64
SetWinner             38309 non-null int64
GameNo                38308 non-null float64
GameWinner            38309 non-null int64
PointNumber           38309 non-null int64
PointWinner           38308 non-null float64
PointServer           38308 non-null float64
Speed_KMH             38308 non-null float64
Rally                 0 non-null float64
P1Score               38308 non-null object
P2Score               38308 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           38308 non-null float64
P2PointsWon           38308 non-null float64
P1Ace                 38309 non-null int64
P2Ace                 38309 non-null int64
P1Winner              38309 non-null int64
P2Winner              38309 non-null int64
P1DoubleFault         38309 non-null int64
P2DoubleFault         38309 non-null int64
P1UnfErr              38309 non-null int64
P2UnfErr              38309 non-null int64
P1NetPoint            38309 non-null int64
P2NetPoint            38309 non-null int64
P1NetPointWon         38309 non-null int64
P2NetPointWon         38309 non-null int64
P1BreakPoint          38309 non-null int64
P2BreakPoint          38309 non-null int64
P1BreakPointWon       38309 non-null int64
P2BreakPointWon       38309 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               38099 non-null float64
Speed_MPH             38308 non-null float64
P1BreakPointMissed    38309 non-null int64
P2BreakPointMissed    38309 non-null int64
ServeIndicator        38309 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           38308 non-null float64
WinnerType            38309 non-null object
WinnerShotType        38309 non-null object
dtypes: float64(31), int64(22), object(6)
memory usage: 17.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41312 entries, 0 to 41311
Data columns (total 61 columns):
match_id              41312 non-null object
ElapsedTime           41312 non-null object
SetNo                 41312 non-null int64
P1GamesWon            41312 non-null int64
P2GamesWon            41312 non-null int64
SetWinner             41312 non-null int64
GameNo                41312 non-null int64
GameWinner            41312 non-null int64
PointNumber           41312 non-null int64
PointWinner           41312 non-null int64
PointServer           41312 non-null int64
Speed_KMH             41312 non-null int64
Rally                 0 non-null float64
P1Score               41312 non-null object
P2Score               41312 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           41312 non-null int64
P2PointsWon           41312 non-null int64
P1Ace                 41312 non-null int64
P2Ace                 41312 non-null int64
P1Winner              41312 non-null int64
P2Winner              41312 non-null int64
P1DoubleFault         41312 non-null int64
P2DoubleFault         41312 non-null int64
P1UnfErr              41312 non-null int64
P2UnfErr              41312 non-null int64
P1NetPoint            41312 non-null int64
P2NetPoint            41312 non-null int64
P1NetPointWon         41312 non-null int64
P2NetPointWon         41312 non-null int64
P1BreakPoint          41312 non-null int64
P2BreakPoint          41312 non-null int64
P1BreakPointWon       41312 non-null int64
P2BreakPointWon       41312 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               41081 non-null float64
Speed_MPH             41312 non-null int64
P1BreakPointMissed    41312 non-null int64
P2BreakPointMissed    41312 non-null int64
ServeIndicator        41312 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           41312 non-null int64
WinnerType            41312 non-null object
WinnerShotType        41312 non-null object
P1DistanceRun         41312 non-null float64
P2DistanceRun         41312 non-null float64
dtypes: float64(22), int64(33), object(6)
memory usage: 19.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43933 entries, 0 to 43932
Data columns (total 65 columns):
match_id              43933 non-null object
ElapsedTime           43933 non-null object
SetNo                 43933 non-null int64
P1GamesWon            43933 non-null int64
P2GamesWon            43933 non-null int64
SetWinner             43933 non-null int64
GameNo                43933 non-null int64
GameWinner            43933 non-null int64
PointNumber           43933 non-null int64
PointWinner           43933 non-null int64
PointServer           43933 non-null int64
Speed_KMH             43933 non-null int64
Rally                 0 non-null float64
P1Score               43933 non-null object
P2Score               43933 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           43933 non-null int64
P2PointsWon           43933 non-null int64
P1Ace                 43933 non-null int64
P2Ace                 43933 non-null int64
P1Winner              43933 non-null int64
P2Winner              43933 non-null int64
P1DoubleFault         43933 non-null int64
P2DoubleFault         43933 non-null int64
P1UnfErr              43933 non-null int64
P2UnfErr              43933 non-null int64
P1NetPoint            43933 non-null int64
P2NetPoint            43933 non-null int64
P1NetPointWon         43933 non-null int64
P2NetPointWon         43933 non-null int64
P1BreakPoint          43933 non-null int64
P2BreakPoint          43933 non-null int64
P1BreakPointWon       43933 non-null int64
P2BreakPointWon       43933 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               43696 non-null float64
Speed_MPH             43933 non-null int64
P1BreakPointMissed    43933 non-null int64
P2BreakPointMissed    43933 non-null int64
ServeIndicator        43933 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           43933 non-null int64
WinnerType            43933 non-null object
WinnerShotType        43933 non-null object
P1DistanceRun         43933 non-null float64
P2DistanceRun         43933 non-null float64
RallyCount            43933 non-null int64
ServeWidth            30174 non-null object
ServeDepth            30174 non-null object
ReturnDepth           24531 non-null object
dtypes: float64(22), int64(34), object(9)
memory usage: 21.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27309 entries, 0 to 27308
Data columns (total 56 columns):
match_id              27309 non-null object
ElapsedTime           27309 non-null object
SetNo                 27309 non-null int64
P1GamesWon            27309 non-null int64
P2GamesWon            27309 non-null int64
SetWinner             27309 non-null int64
GameNo                27309 non-null int64
GameWinner            27309 non-null int64
PointNumber           27309 non-null int64
PointWinner           27309 non-null int64
PointServer           27309 non-null int64
Speed_KMH             27309 non-null int64
Rally                 27309 non-null int64
P1Score               27309 non-null object
P2Score               27309 non-null object
P1Momentum            27309 non-null int64
P2Momentum            27309 non-null int64
P1PointsWon           27309 non-null int64
P2PointsWon           27309 non-null int64
P1Ace                 27309 non-null int64
P2Ace                 27309 non-null int64
P1Winner              27309 non-null int64
P2Winner              27309 non-null int64
P1DoubleFault         27309 non-null int64
P2DoubleFault         27309 non-null int64
P1UnfErr              27309 non-null int64
P2UnfErr              27309 non-null int64
P1NetPoint            27309 non-null int64
P2NetPoint            27309 non-null int64
P1NetPointWon         27309 non-null int64
P2NetPointWon         27309 non-null int64
P1BreakPoint          27309 non-null int64
P2BreakPoint          27309 non-null int64
P1BreakPointWon       27309 non-null int64
P2BreakPointWon       27309 non-null int64
P1FirstSrvIn          27309 non-null int64
P2FirstSrvIn          27309 non-null int64
P1FirstSrvWon         27309 non-null int64
P2FirstSrvWon         27309 non-null int64
P1SecondSrvIn         27309 non-null int64
P2SecondSrvIn         27309 non-null int64
P1SecondSrvWon        27309 non-null int64
P2SecondSrvWon        27309 non-null int64
P1ForcedError         27309 non-null int64
P2ForcedError         27309 non-null int64
History               27309 non-null int64
Speed_MPH             27309 non-null int64
P1BreakPointMissed    27309 non-null int64
P2BreakPointMissed    27309 non-null int64
ServeIndicator        27309 non-null int64
Serve_Direction       27309 non-null int64
Winner_FH             27309 non-null int64
Winner_BH             27309 non-null int64
ServingTo             27309 non-null object
P1TurningPoint        27309 non-null int64
P2TurningPoint        27309 non-null int64
dtypes: int64(51), object(5)
memory usage: 11.7+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30975 entries, 0 to 30974
Data columns (total 56 columns):
match_id              30975 non-null object
ElapsedTime           30975 non-null object
SetNo                 30972 non-null float64
P1GamesWon            30972 non-null float64
P2GamesWon            30972 non-null float64
SetWinner             30975 non-null int64
GameNo                30972 non-null float64
GameWinner            30975 non-null int64
PointNumber           30975 non-null int64
PointWinner           30972 non-null float64
PointServer           30972 non-null float64
Speed_KMH             30972 non-null float64
Rally                 0 non-null float64
P1Score               30972 non-null object
P2Score               30972 non-null object
P1Momentum            30975 non-null int64
P2Momentum            30975 non-null int64
P1PointsWon           30972 non-null float64
P2PointsWon           30972 non-null float64
P1Ace                 30975 non-null int64
P2Ace                 30975 non-null int64
P1Winner              30975 non-null int64
P2Winner              30975 non-null int64
P1DoubleFault         30975 non-null int64
P2DoubleFault         30975 non-null int64
P1UnfErr              30975 non-null int64
P2UnfErr              30975 non-null int64
P1NetPoint            30975 non-null int64
P2NetPoint            30975 non-null int64
P1NetPointWon         30975 non-null int64
P2NetPointWon         30975 non-null int64
P1BreakPoint          30975 non-null int64
P2BreakPoint          30975 non-null int64
P1BreakPointWon       30975 non-null int64
P2BreakPointWon       30975 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               30972 non-null float64
Speed_MPH             30972 non-null float64
P1BreakPointMissed    30975 non-null int64
P2BreakPointMissed    30975 non-null int64
ServeIndicator        30975 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1557 non-null object
P2TurningPoint        1559 non-null object
dtypes: float64(26), int64(24), object(6)
memory usage: 13.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30353 entries, 0 to 30352
Data columns (total 56 columns):
match_id              30353 non-null object
ElapsedTime           30353 non-null object
SetNo                 30353 non-null int64
P1GamesWon            30353 non-null int64
P2GamesWon            30353 non-null int64
SetWinner             30353 non-null int64
GameNo                30353 non-null int64
GameWinner            30353 non-null int64
PointNumber           30353 non-null int64
PointWinner           30353 non-null int64
PointServer           30353 non-null int64
Speed_KMH             30353 non-null int64
Rally                 0 non-null float64
P1Score               30353 non-null object
P2Score               30353 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           30353 non-null int64
P2PointsWon           30353 non-null int64
P1Ace                 30353 non-null int64
P2Ace                 30353 non-null int64
P1Winner              30353 non-null int64
P2Winner              30353 non-null int64
P1DoubleFault         30353 non-null int64
P2DoubleFault         30353 non-null int64
P1UnfErr              30353 non-null int64
P2UnfErr              30353 non-null int64
P1NetPoint            30353 non-null int64
P2NetPoint            30353 non-null int64
P1NetPointWon         30353 non-null int64
P2NetPointWon         30353 non-null int64
P1BreakPoint          30353 non-null int64
P2BreakPoint          30353 non-null int64
P1BreakPointWon       30353 non-null int64
P2BreakPointWon       30353 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               30353 non-null int64
Speed_MPH             30353 non-null int64
P1BreakPointMissed    30353 non-null int64
P2BreakPointMissed    30353 non-null int64
ServeIndicator        30353 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
dtypes: float64(19), int64(33), object(4)
memory usage: 13.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33159 entries, 0 to 33158
Data columns (total 59 columns):
match_id              33159 non-null object
ElapsedTime           33159 non-null object
SetNo                 33157 non-null float64
P1GamesWon            33157 non-null float64
P2GamesWon            33157 non-null float64
SetWinner             33159 non-null int64
GameNo                33157 non-null float64
GameWinner            33159 non-null int64
PointNumber           33159 non-null int64
PointWinner           33157 non-null float64
PointServer           33157 non-null float64
Speed_KMH             33157 non-null float64
Rally                 0 non-null float64
P1Score               33157 non-null object
P2Score               33157 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           33157 non-null float64
P2PointsWon           33157 non-null float64
P1Ace                 33159 non-null int64
P2Ace                 33159 non-null int64
P1Winner              33159 non-null int64
P2Winner              33159 non-null int64
P1DoubleFault         33159 non-null int64
P2DoubleFault         33159 non-null int64
P1UnfErr              33159 non-null int64
P2UnfErr              33159 non-null int64
P1NetPoint            33159 non-null int64
P2NetPoint            33159 non-null int64
P1NetPointWon         33159 non-null int64
P2NetPointWon         33159 non-null int64
P1BreakPoint          33159 non-null int64
P2BreakPoint          33159 non-null int64
P1BreakPointWon       33159 non-null int64
P2BreakPointWon       33159 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               32970 non-null float64
Speed_MPH             33157 non-null float64
P1BreakPointMissed    33159 non-null int64
P2BreakPointMissed    33159 non-null int64
ServeIndicator        33159 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           33157 non-null float64
WinnerType            33159 non-null object
WinnerShotType        33159 non-null object
dtypes: float64(31), int64(22), object(6)
memory usage: 14.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31442 entries, 0 to 31441
Data columns (total 61 columns):
match_id              31442 non-null object
ElapsedTime           31442 non-null object
SetNo                 31442 non-null int64
P1GamesWon            31442 non-null int64
P2GamesWon            31442 non-null int64
SetWinner             31442 non-null int64
GameNo                31442 non-null int64
GameWinner            31442 non-null int64
PointNumber           31442 non-null int64
PointWinner           31442 non-null int64
PointServer           31442 non-null int64
Speed_KMH             31442 non-null int64
Rally                 0 non-null float64
P1Score               31442 non-null object
P2Score               31442 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           31442 non-null int64
P2PointsWon           31442 non-null int64
P1Ace                 31442 non-null int64
P2Ace                 31442 non-null int64
P1Winner              31442 non-null int64
P2Winner              31442 non-null int64
P1DoubleFault         31442 non-null int64
P2DoubleFault         31442 non-null int64
P1UnfErr              31442 non-null int64
P2UnfErr              31442 non-null int64
P1NetPoint            31442 non-null int64
P2NetPoint            31442 non-null int64
P1NetPointWon         31442 non-null int64
P2NetPointWon         31442 non-null int64
P1BreakPoint          31442 non-null int64
P2BreakPoint          31442 non-null int64
P1BreakPointWon       31442 non-null int64
P2BreakPointWon       31442 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               31266 non-null float64
Speed_MPH             31442 non-null int64
P1BreakPointMissed    31442 non-null int64
P2BreakPointMissed    31442 non-null int64
ServeIndicator        31442 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           31442 non-null int64
WinnerType            31442 non-null object
WinnerShotType        31442 non-null object
P1DistanceRun         31442 non-null float64
P2DistanceRun         31442 non-null float64
dtypes: float64(22), int64(33), object(6)
memory usage: 14.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30606 entries, 0 to 30605
Data columns (total 65 columns):
match_id              30606 non-null object
ElapsedTime           30606 non-null object
SetNo                 30606 non-null int64
P1GamesWon            30606 non-null int64
P2GamesWon            30606 non-null int64
SetWinner             30606 non-null int64
GameNo                30606 non-null int64
GameWinner            30606 non-null int64
PointNumber           30606 non-null int64
PointWinner           30606 non-null int64
PointServer           30606 non-null int64
Speed_KMH             30606 non-null int64
Rally                 0 non-null float64
P1Score               30606 non-null object
P2Score               30606 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           30606 non-null int64
P2PointsWon           30606 non-null int64
P1Ace                 30606 non-null int64
P2Ace                 30606 non-null int64
P1Winner              30606 non-null int64
P2Winner              30606 non-null int64
P1DoubleFault         30606 non-null int64
P2DoubleFault         30606 non-null int64
P1UnfErr              30606 non-null int64
P2UnfErr              30606 non-null int64
P1NetPoint            30606 non-null int64
P2NetPoint            30606 non-null int64
P1NetPointWon         30606 non-null int64
P2NetPointWon         30606 non-null int64
P1BreakPoint          30606 non-null int64
P2BreakPoint          30606 non-null int64
P1BreakPointWon       30606 non-null int64
P2BreakPointWon       30606 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               30434 non-null float64
Speed_MPH             30606 non-null int64
P1BreakPointMissed    30606 non-null int64
P2BreakPointMissed    30606 non-null int64
ServeIndicator        30606 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           30606 non-null int64
WinnerType            30606 non-null object
WinnerShotType        30606 non-null object
P1DistanceRun         30606 non-null float64
P2DistanceRun         30606 non-null float64
RallyCount            30606 non-null int64
ServeWidth            23567 non-null object
ServeDepth            23567 non-null object
ReturnDepth           19389 non-null object
dtypes: float64(22), int64(34), object(9)
memory usage: 15.2+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30067 entries, 0 to 30066
Data columns (total 65 columns):
match_id              30067 non-null object
ElapsedTime           30067 non-null object
SetNo                 30067 non-null int64
P1GamesWon            30067 non-null int64
P2GamesWon            30067 non-null int64
SetWinner             30067 non-null int64
GameNo                30067 non-null int64
GameWinner            30067 non-null int64
PointNumber           30067 non-null object
PointWinner           30067 non-null int64
PointServer           30067 non-null int64
Speed_KMH             30067 non-null int64
Rally                 0 non-null float64
P1Score               30067 non-null object
P2Score               30067 non-null object
P1Momentum            30067 non-null int64
P2Momentum            30067 non-null int64
P1PointsWon           30067 non-null int64
P2PointsWon           30067 non-null int64
P1Ace                 30067 non-null int64
P2Ace                 30067 non-null int64
P1Winner              30067 non-null int64
P2Winner              30067 non-null int64
P1DoubleFault         30067 non-null int64
P2DoubleFault         30067 non-null int64
P1UnfErr              30067 non-null int64
P2UnfErr              30067 non-null int64
P1NetPoint            30067 non-null int64
P2NetPoint            30067 non-null int64
P1NetPointWon         30067 non-null int64
P2NetPointWon         30067 non-null int64
P1BreakPoint          30067 non-null int64
P2BreakPoint          30067 non-null int64
P1BreakPointWon       30067 non-null int64
P2BreakPointWon       30067 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               29721 non-null float64
Speed_MPH             30067 non-null int64
P1BreakPointMissed    30067 non-null int64
P2BreakPointMissed    30067 non-null int64
ServeIndicator        30067 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           30067 non-null int64
WinnerType            30067 non-null object
WinnerShotType        30067 non-null object
P1DistanceRun         30067 non-null float64
P2DistanceRun         30067 non-null float64
RallyCount            30067 non-null int64
ServeWidth            28519 non-null object
ServeDepth            28519 non-null object
ReturnDepth           23783 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 14.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31851 entries, 0 to 31850
Data columns (total 65 columns):
match_id              31851 non-null object
ElapsedTime           31851 non-null object
SetNo                 31851 non-null int64
P1GamesWon            31851 non-null int64
P2GamesWon            31851 non-null int64
SetWinner             31851 non-null int64
GameNo                31851 non-null int64
GameWinner            31851 non-null int64
PointNumber           31851 non-null object
PointWinner           31851 non-null int64
PointServer           31851 non-null int64
Speed_KMH             31851 non-null int64
Rally                 0 non-null float64
P1Score               31851 non-null object
P2Score               31851 non-null object
P1Momentum            31851 non-null int64
P2Momentum            31851 non-null int64
P1PointsWon           31851 non-null int64
P2PointsWon           31851 non-null int64
P1Ace                 31851 non-null int64
P2Ace                 31851 non-null int64
P1Winner              31851 non-null int64
P2Winner              31851 non-null int64
P1DoubleFault         31851 non-null int64
P2DoubleFault         31851 non-null int64
P1UnfErr              31851 non-null int64
P2UnfErr              31851 non-null int64
P1NetPoint            31851 non-null int64
P2NetPoint            31851 non-null int64
P1NetPointWon         31851 non-null int64
P2NetPointWon         31851 non-null int64
P1BreakPoint          31851 non-null int64
P2BreakPoint          31851 non-null int64
P1BreakPointWon       31851 non-null int64
P2BreakPointWon       31851 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               31495 non-null float64
Speed_MPH             31851 non-null int64
P1BreakPointMissed    31851 non-null int64
P2BreakPointMissed    31851 non-null int64
ServeIndicator        31851 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           31851 non-null int64
WinnerType            31851 non-null object
WinnerShotType        31851 non-null object
P1DistanceRun         31851 non-null float64
P2DistanceRun         31851 non-null float64
RallyCount            31851 non-null int64
ServeWidth            29429 non-null object
ServeDepth            29429 non-null object
ReturnDepth           23947 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 15.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47893 entries, 0 to 47892
Data columns (total 65 columns):
match_id              47893 non-null object
ElapsedTime           47893 non-null object
SetNo                 47893 non-null int64
P1GamesWon            47893 non-null int64
P2GamesWon            47893 non-null int64
SetWinner             47893 non-null int64
GameNo                47893 non-null int64
GameWinner            47893 non-null int64
PointNumber           47893 non-null object
PointWinner           47893 non-null int64
PointServer           47893 non-null int64
Speed_KMH             47893 non-null int64
Rally                 0 non-null float64
P1Score               47893 non-null object
P2Score               47893 non-null object
P1Momentum            47893 non-null int64
P2Momentum            47893 non-null int64
P1PointsWon           47893 non-null int64
P2PointsWon           47893 non-null int64
P1Ace                 47893 non-null int64
P2Ace                 47893 non-null int64
P1Winner              47893 non-null int64
P2Winner              47893 non-null int64
P1DoubleFault         47893 non-null int64
P2DoubleFault         47893 non-null int64
P1UnfErr              47893 non-null int64
P2UnfErr              47893 non-null int64
P1NetPoint            47893 non-null int64
P2NetPoint            47893 non-null int64
P1NetPointWon         47893 non-null int64
P2NetPointWon         47893 non-null int64
P1BreakPoint          47893 non-null int64
P2BreakPoint          47893 non-null int64
P1BreakPointWon       47893 non-null int64
P2BreakPointWon       47893 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               47391 non-null float64
Speed_MPH             47893 non-null int64
P1BreakPointMissed    47893 non-null int64
P2BreakPointMissed    47893 non-null int64
ServeIndicator        47893 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           47893 non-null int64
WinnerType            47893 non-null object
WinnerShotType        47893 non-null object
P1DistanceRun         47893 non-null float64
P2DistanceRun         47893 non-null float64
RallyCount            47893 non-null int64
ServeWidth            25970 non-null object
ServeDepth            25970 non-null object
ReturnDepth           21183 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 23.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34340 entries, 0 to 34339
Data columns (total 55 columns):
match_id              34340 non-null object
ElapsedTime           34340 non-null object
SetNo                 34339 non-null float64
P1GamesWon            34339 non-null float64
P2GamesWon            34339 non-null float64
SetWinner             34340 non-null int64
GameNo                34339 non-null float64
GameWinner            34340 non-null int64
PointNumber           34340 non-null int64
PointWinner           34339 non-null float64
PointServer           34339 non-null float64
Speed_KMH             34339 non-null float64
Rally                 34339 non-null float64
P1Score               34339 non-null object
P2Score               34339 non-null object
P1Momentum            34340 non-null int64
P2Momentum            34340 non-null int64
P1PointsWon           34339 non-null float64
P2PointsWon           34339 non-null float64
P1Ace                 34339 non-null float64
P2Ace                 34339 non-null float64
P1Winner              34339 non-null float64
P2Winner              34339 non-null float64
P1DoubleFault         34339 non-null float64
P2DoubleFault         34339 non-null float64
P1UnfErr              34339 non-null float64
P2UnfErr              34339 non-null float64
P1NetPoint            34340 non-null int64
P2NetPoint            34340 non-null int64
P1NetPointWon         34340 non-null int64
P2NetPointWon         34340 non-null int64
P1BreakPoint          34340 non-null int64
P2BreakPoint          34340 non-null int64
P1BreakPointWon       34340 non-null int64
P2BreakPointWon       34340 non-null int64
P1FirstSrvIn          34339 non-null float64
P2FirstSrvIn          34339 non-null float64
P1FirstSrvWon         34339 non-null float64
P2FirstSrvWon         34339 non-null float64
P1SecondSrvIn         34339 non-null float64
P2SecondSrvIn         34339 non-null float64
P1SecondSrvWon        34339 non-null float64
P2SecondSrvWon        34339 non-null float64
P1ForcedError         34339 non-null float64
P2ForcedError         34339 non-null float64
History               34339 non-null float64
Speed_MPH             34339 non-null float64
P1BreakPointMissed    34340 non-null int64
P2BreakPointMissed    34340 non-null int64
ServeIndicator        34340 non-null int64
Serve_Direction       34339 non-null float64
Winner_FH             34339 non-null float64
Winner_BH             34339 non-null float64
P1TurningPoint        34340 non-null int64
P2TurningPoint        34340 non-null int64
dtypes: float64(33), int64(18), object(4)
memory usage: 14.4+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31184 entries, 0 to 31183
Data columns (total 56 columns):
match_id              31184 non-null object
ElapsedTime           31184 non-null object
SetNo                 30699 non-null float64
P1GamesWon            30699 non-null float64
P2GamesWon            30699 non-null float64
SetWinner             31184 non-null int64
GameNo                30699 non-null float64
GameWinner            31184 non-null int64
PointNumber           31184 non-null int64
PointWinner           30699 non-null float64
PointServer           30699 non-null float64
Speed_KMH             30699 non-null float64
Rally                 0 non-null float64
P1Score               30699 non-null object
P2Score               30699 non-null object
P1Momentum            31184 non-null int64
P2Momentum            31184 non-null int64
P1PointsWon           30699 non-null float64
P2PointsWon           30699 non-null float64
P1Ace                 31184 non-null int64
P2Ace                 31184 non-null int64
P1Winner              31184 non-null int64
P2Winner              31184 non-null int64
P1DoubleFault         31184 non-null int64
P2DoubleFault         31184 non-null int64
P1UnfErr              31184 non-null int64
P2UnfErr              31184 non-null int64
P1NetPoint            31184 non-null int64
P2NetPoint            31184 non-null int64
P1NetPointWon         31184 non-null int64
P2NetPointWon         31184 non-null int64
P1BreakPoint          31184 non-null int64
P2BreakPoint          31184 non-null int64
P1BreakPointWon       31184 non-null int64
P2BreakPointWon       31184 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               30699 non-null float64
Speed_MPH             30699 non-null float64
P1BreakPointMissed    31184 non-null int64
P2BreakPointMissed    31184 non-null int64
ServeIndicator        31184 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1551 non-null object
P2TurningPoint        1548 non-null object
dtypes: float64(26), int64(24), object(6)
memory usage: 13.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33248 entries, 0 to 33247
Data columns (total 56 columns):
match_id              33248 non-null object
ElapsedTime           33248 non-null object
SetNo                 33209 non-null float64
P1GamesWon            33209 non-null float64
P2GamesWon            33209 non-null float64
SetWinner             33248 non-null int64
GameNo                33209 non-null float64
GameWinner            33248 non-null int64
PointNumber           33248 non-null int64
PointWinner           33209 non-null float64
PointServer           33209 non-null float64
Speed_KMH             33209 non-null float64
Rally                 0 non-null float64
P1Score               33209 non-null object
P2Score               33209 non-null object
P1Momentum            33248 non-null int64
P2Momentum            33248 non-null int64
P1PointsWon           33209 non-null float64
P2PointsWon           33209 non-null float64
P1Ace                 33248 non-null int64
P2Ace                 33248 non-null int64
P1Winner              33248 non-null int64
P2Winner              33248 non-null int64
P1DoubleFault         33248 non-null int64
P2DoubleFault         33248 non-null int64
P1UnfErr              33248 non-null int64
P2UnfErr              33248 non-null int64
P1NetPoint            33248 non-null int64
P2NetPoint            33248 non-null int64
P1NetPointWon         33248 non-null int64
P2NetPointWon         33248 non-null int64
P1BreakPoint          33248 non-null int64
P2BreakPoint          33248 non-null int64
P1BreakPointWon       33248 non-null int64
P2BreakPointWon       33248 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               33209 non-null float64
Speed_MPH             33209 non-null float64
P1BreakPointMissed    33248 non-null int64
P2BreakPointMissed    33248 non-null int64
ServeIndicator        33248 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1647 non-null object
P2TurningPoint        1646 non-null object
dtypes: float64(26), int64(24), object(6)
memory usage: 14.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44426 entries, 0 to 44425
Data columns (total 59 columns):
match_id              44426 non-null object
ElapsedTime           44426 non-null object
SetNo                 44344 non-null float64
P1GamesWon            44344 non-null float64
P2GamesWon            44344 non-null float64
SetWinner             44426 non-null int64
GameNo                44344 non-null float64
GameWinner            44426 non-null int64
PointNumber           44426 non-null int64
PointWinner           44344 non-null float64
PointServer           44344 non-null float64
Speed_KMH             44344 non-null float64
Rally                 0 non-null float64
P1Score               44344 non-null object
P2Score               44344 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           44344 non-null float64
P2PointsWon           44344 non-null float64
P1Ace                 44426 non-null int64
P2Ace                 44426 non-null int64
P1Winner              44426 non-null int64
P2Winner              44426 non-null int64
P1DoubleFault         44426 non-null int64
P2DoubleFault         44426 non-null int64
P1UnfErr              44426 non-null int64
P2UnfErr              44426 non-null int64
P1NetPoint            44426 non-null int64
P2NetPoint            44426 non-null int64
P1NetPointWon         44426 non-null int64
P2NetPointWon         44426 non-null int64
P1BreakPoint          44426 non-null int64
P2BreakPoint          44426 non-null int64
P1BreakPointWon       44426 non-null int64
P2BreakPointWon       44426 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               44090 non-null float64
Speed_MPH             44344 non-null float64
P1BreakPointMissed    44426 non-null int64
P2BreakPointMissed    44426 non-null int64
ServeIndicator        44426 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           44344 non-null float64
WinnerType            44426 non-null object
WinnerShotType        44426 non-null object
dtypes: float64(31), int64(22), object(6)
memory usage: 20.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37208 entries, 0 to 37207
Data columns (total 61 columns):
match_id              37208 non-null object
ElapsedTime           37208 non-null object
SetNo                 37187 non-null float64
P1GamesWon            37187 non-null float64
P2GamesWon            37187 non-null float64
SetWinner             37208 non-null int64
GameNo                37187 non-null float64
GameWinner            37208 non-null int64
PointNumber           37208 non-null int64
PointWinner           37187 non-null float64
PointServer           37187 non-null float64
Speed_KMH             37187 non-null float64
Rally                 0 non-null float64
P1Score               37187 non-null object
P2Score               37187 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           37187 non-null float64
P2PointsWon           37187 non-null float64
P1Ace                 37208 non-null int64
P2Ace                 37208 non-null int64
P1Winner              37208 non-null int64
P2Winner              37208 non-null int64
P1DoubleFault         37208 non-null int64
P2DoubleFault         37208 non-null int64
P1UnfErr              37208 non-null int64
P2UnfErr              37208 non-null int64
P1NetPoint            37208 non-null int64
P2NetPoint            37208 non-null int64
P1NetPointWon         37208 non-null int64
P2NetPointWon         37208 non-null int64
P1BreakPoint          37208 non-null int64
P2BreakPoint          37208 non-null int64
P1BreakPointWon       37208 non-null int64
P2BreakPointWon       37208 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               36979 non-null float64
Speed_MPH             37187 non-null float64
P1BreakPointMissed    37208 non-null int64
P2BreakPointMissed    37208 non-null int64
ServeIndicator        37208 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           37187 non-null float64
WinnerType            37208 non-null object
WinnerShotType        37208 non-null object
P1DistanceRun         37208 non-null float64
P2DistanceRun         37208 non-null float64
dtypes: float64(33), int64(22), object(6)
memory usage: 17.3+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32165 entries, 0 to 32164
Data columns (total 65 columns):
match_id              32165 non-null object
ElapsedTime           32165 non-null object
SetNo                 32165 non-null int64
P1GamesWon            32165 non-null int64
P2GamesWon            32165 non-null int64
SetWinner             32165 non-null int64
GameNo                32165 non-null int64
GameWinner            32165 non-null int64
PointNumber           32165 non-null int64
PointWinner           32165 non-null int64
PointServer           32165 non-null int64
Speed_KMH             32165 non-null int64
Rally                 0 non-null float64
P1Score               32165 non-null object
P2Score               32165 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           32165 non-null int64
P2PointsWon           32165 non-null int64
P1Ace                 32165 non-null int64
P2Ace                 32165 non-null int64
P1Winner              32165 non-null int64
P2Winner              32165 non-null int64
P1DoubleFault         32165 non-null int64
P2DoubleFault         32165 non-null int64
P1UnfErr              32165 non-null int64
P2UnfErr              32165 non-null int64
P1NetPoint            32165 non-null int64
P2NetPoint            32165 non-null int64
P1NetPointWon         32165 non-null int64
P2NetPointWon         32165 non-null int64
P1BreakPoint          32165 non-null int64
P2BreakPoint          32165 non-null int64
P1BreakPointWon       32165 non-null int64
P2BreakPointWon       32165 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               31989 non-null float64
Speed_MPH             32165 non-null int64
P1BreakPointMissed    32165 non-null int64
P2BreakPointMissed    32165 non-null int64
ServeIndicator        32165 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           32165 non-null int64
WinnerType            32165 non-null object
WinnerShotType        32165 non-null object
P1DistanceRun         32165 non-null float64
P2DistanceRun         32165 non-null float64
RallyCount            32165 non-null int64
ServeWidth            11657 non-null object
ServeDepth            11657 non-null object
ReturnDepth           10078 non-null object
dtypes: float64(22), int64(34), object(9)
memory usage: 16.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43122 entries, 0 to 43121
Data columns (total 65 columns):
match_id              43122 non-null object
ElapsedTime           43122 non-null object
SetNo                 43122 non-null int64
P1GamesWon            43122 non-null int64
P2GamesWon            43122 non-null int64
SetWinner             43122 non-null int64
GameNo                43122 non-null int64
GameWinner            43122 non-null int64
PointNumber           43122 non-null int64
PointWinner           43122 non-null int64
PointServer           43122 non-null int64
Speed_KMH             43122 non-null int64
Rally                 0 non-null float64
P1Score               43122 non-null object
P2Score               43122 non-null object
P1Momentum            0 non-null float64
P2Momentum            0 non-null float64
P1PointsWon           43122 non-null int64
P2PointsWon           43122 non-null int64
P1Ace                 43122 non-null int64
P2Ace                 43122 non-null int64
P1Winner              43122 non-null int64
P2Winner              43122 non-null int64
P1DoubleFault         43122 non-null int64
P2DoubleFault         43122 non-null int64
P1UnfErr              43122 non-null int64
P2UnfErr              43122 non-null int64
P1NetPoint            43122 non-null int64
P2NetPoint            43122 non-null int64
P1NetPointWon         43122 non-null int64
P2NetPointWon         43122 non-null int64
P1BreakPoint          43122 non-null int64
P2BreakPoint          43122 non-null int64
P1BreakPointWon       43122 non-null int64
P2BreakPointWon       43122 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               42880 non-null float64
Speed_MPH             43122 non-null int64
P1BreakPointMissed    43122 non-null int64
P2BreakPointMissed    43122 non-null int64
ServeIndicator        43122 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           43122 non-null int64
WinnerType            43122 non-null object
WinnerShotType        43122 non-null object
P1DistanceRun         43122 non-null float64
P2DistanceRun         43122 non-null float64
RallyCount            43122 non-null int64
ServeWidth            11828 non-null object
ServeDepth            11828 non-null object
ReturnDepth           10400 non-null object
dtypes: float64(22), int64(34), object(9)
memory usage: 21.4+ MB

In [60]:
pts_2012_usopen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30975 entries, 0 to 30974
Data columns (total 56 columns):
match_id              30975 non-null object
ElapsedTime           30975 non-null object
SetNo                 30972 non-null float64
P1GamesWon            30972 non-null float64
P2GamesWon            30972 non-null float64
SetWinner             30975 non-null int64
GameNo                30972 non-null float64
GameWinner            30975 non-null int64
PointNumber           30975 non-null int64
PointWinner           30972 non-null float64
PointServer           30972 non-null float64
Speed_KMH             30972 non-null float64
Rally                 0 non-null float64
P1Score               30972 non-null object
P2Score               30972 non-null object
P1Momentum            30975 non-null int64
P2Momentum            30975 non-null int64
P1PointsWon           30972 non-null float64
P2PointsWon           30972 non-null float64
P1Ace                 30975 non-null int64
P2Ace                 30975 non-null int64
P1Winner              30975 non-null int64
P2Winner              30975 non-null int64
P1DoubleFault         30975 non-null int64
P2DoubleFault         30975 non-null int64
P1UnfErr              30975 non-null int64
P2UnfErr              30975 non-null int64
P1NetPoint            30975 non-null int64
P2NetPoint            30975 non-null int64
P1NetPointWon         30975 non-null int64
P2NetPointWon         30975 non-null int64
P1BreakPoint          30975 non-null int64
P2BreakPoint          30975 non-null int64
P1BreakPointWon       30975 non-null int64
P2BreakPointWon       30975 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               30972 non-null float64
Speed_MPH             30972 non-null float64
P1BreakPointMissed    30975 non-null int64
P2BreakPointMissed    30975 non-null int64
ServeIndicator        30975 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        1557 non-null object
P2TurningPoint        1559 non-null object
dtypes: float64(26), int64(24), object(6)
memory usage: 13.2+ MB

In [63]:
pts_2012_usopen.P1NetPointWon.value_counts()

0    28948
1     2027
Name: P1NetPointWon, dtype: int64

In [55]:
pts_2011_usopen.columns

Index(['match_id', 'ElapsedTime', 'SetNo', 'P1GamesWon', 'P2GamesWon',
       'SetWinner', 'GameNo', 'GameWinner', 'PointNumber', 'PointWinner',
       'PointServer', 'Speed_KMH', 'Rally', 'P1Score', 'P2Score', 'P1Momentum',
       'P2Momentum', 'P1PointsWon', 'P2PointsWon', 'P1Ace', 'P2Ace',
       'P1Winner', 'P2Winner', 'P1DoubleFault', 'P2DoubleFault', 'P1UnfErr',
       'P2UnfErr', 'P1NetPoint', 'P2NetPoint', 'P1NetPointWon',
       'P2NetPointWon', 'P1BreakPoint', 'P2BreakPoint', 'P1BreakPointWon',
       'P2BreakPointWon', 'P1FirstSrvIn', 'P2FirstSrvIn', 'P1FirstSrvWon',
       'P2FirstSrvWon', 'P1SecondSrvIn', 'P2SecondSrvIn', 'P1SecondSrvWon',
       'P2SecondSrvWon', 'P1ForcedError', 'P2ForcedError', 'History',
       'Speed_MPH', 'P1BreakPointMissed', 'P2BreakPointMissed',
       'ServeIndicator', 'Serve_Direction', 'Winner_FH', 'Winner_BH',
       'ServingTo', 'P1TurningPoint', 'P2TurningPoint'],
      dtype='object')

In [47]:
pts_2011_usopen.PointWinner.value_counts()

2    13575
1    13573
0      161
Name: PointWinner, dtype: int64

In [59]:
cols = []
for df in list_of_dfs:
    col = df.columns
    cols.extend(col)
unique_cols = set(cols)
len(unique_cols)
unique_cols

{'ElapsedTime',
 'GameNo',
 'GameWinner',
 'History',
 'P1Ace',
 'P1BreakPoint',
 'P1BreakPointMissed',
 'P1BreakPointWon',
 'P1DistanceRun',
 'P1DoubleFault',
 'P1FirstSrvIn',
 'P1FirstSrvWon',
 'P1ForcedError',
 'P1GamesWon',
 'P1Momentum',
 'P1NetPoint',
 'P1NetPointWon',
 'P1PointsWon',
 'P1Score',
 'P1SecondSrvIn',
 'P1SecondSrvWon',
 'P1TurningPoint',
 'P1UnfErr',
 'P1Winner',
 'P2Ace',
 'P2BreakPoint',
 'P2BreakPointMissed',
 'P2BreakPointWon',
 'P2DistanceRun',
 'P2DoubleFault',
 'P2FirstSrvIn',
 'P2FirstSrvWon',
 'P2ForcedError',
 'P2GamesWon',
 'P2Momentum',
 'P2NetPoint',
 'P2NetPointWon',
 'P2PointsWon',
 'P2Score',
 'P2SecondSrvIn',
 'P2SecondSrvWon',
 'P2TurningPoint',
 'P2UnfErr',
 'P2Winner',
 'PointNumber',
 'PointServer',
 'PointWinner',
 'Rally',
 'RallyCount',
 'ReturnDepth',
 'ServeDepth',
 'ServeIndicator',
 'ServeNumber',
 'ServeWidth',
 'Serve_Direction',
 'ServingTo',
 'SetNo',
 'SetWinner',
 'Speed_KMH',
 'Speed_MPH',
 'WinnerShotType',
 'WinnerType',
 'Winner_BH',
 'Winner_FH',
 'match_id'}

In [50]:
for df in list_of_dfs:
    df = df[df['PointWinner'] != 0]

In [51]:
pts_2011_usopen.PointWinner.value_counts()

2    13575
1    13573
0      161
Name: PointWinner, dtype: int64

In [29]:
hard_court_dfs = [
    pts_2011_ausopen,
    pts_2012_ausopen,
    pts_2013_ausopen,
    pts_2014_ausopen,
    pts_2015_ausopen,
    pts_2016_ausopen,
    pts_2017_ausopen,
    pts_2011_usopen,
    pts_2012_usopen,
    pts_2013_usopen,
    pts_2014_usopen,
    pts_2015_usopen,
    pts_2016_usopen,
    pts_2017_usopen,
    pts_2018_usopen,
    pts_2019_usopen
]

In [ ]:
for df in hard_court_dfs:
    df[df[]]

In [ ]:
# pts_2017_frenchopen.head()

In [3]:
# yrs = ['2011','2012','2013','2014','2015','2016','2017','2018','2019']
# tournaments = ['ausopen','frenchopen','usopen','wimbledon']

In [ ]:
# df_names = {}
# for tournament in tournaments:
#     for yr in yrs:
#         df_name = f"pts_{yr}_{tournament}"
#         d[df_name] = pd.DataFrame()
#         d[df_name] = pd.read_csv('./data/2011-wimbledon-points.csv')
#         df_names.append(df_name)

In [8]:
# def read_csvs(yrs, tournaments):
#     dict_of_dfs = {}
#     for tournament in tournaments:
#         for yr in yrs:
#             path = f"./data/{yr}-{tournament}-points.csv"
#             try:
#                 pd.read_csv(path)
#                 df = f"pts_{yr}_{tournament}"
#                 d[df] = pd.read_csv(path)
#             except:
#                 pass

In [9]:
# read_csvs(yrs,tournaments)

In [ ]:
# # def read_csvs(list_of_yrs, list_of_tournaments):
# list_of_dfs = []
# for yr in yrs:
#     for tournament in tournaments:
#         df = ''
#         path = f"./data/{yr}-{tournament}-points.csv"
#         print(path)
#         try: 
#             print(path)
#             df = pd.read_csv(path)
#             df = f"pts_{yr}_{tournament}"
#             list_of_dfs.append(df)
#         except:
#             pass
# pd.DataFrame(list_of_dfs[0]).head()

In [48]:
pts_2019_usopen.head()

,match_id,ElapsedTime,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointNumber,PointWinner,...,P2TurningPoint,ServeNumber,WinnerType,WinnerShotType,P1DistanceRun,P2DistanceRun,RallyCount,ServeWidth,ServeDepth,ReturnDepth
0,2019-usopen-1101,0:00:00,1,0,0,0,1,0,0X,0,...,NaN,0,0,0,0.000,0.000,0,NaN,NaN,NaN
1,2019-usopen-1101,0:00:00,1,0,0,0,1,0,0Y,0,...,NaN,0,0,0,0.000,0.000,0,NaN,NaN,NaN
2,2019-usopen-1101,0:00:00,1,0,0,0,1,0,1,1,...,NaN,2,0,0,29.095,33.480,9,BC,NCTL,D
3,2019-usopen-1101,0:00:55,1,0,0,0,1,0,2,2,...,NaN,0,0,0,0.577,0.510,0,NaN,NaN,NaN
4,2019-usopen-1101,0:01:22,1,0,0,0,1,0,3,1,...,NaN,1,0,0,14.642,8.791,5,C,NCTL,ND

In [65]:
pts_2019_usopen = pts_2019_usopen[pts_2019_usopen['PointWinner'] != 0]

In [66]:
pts_2019_usopen.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47391 entries, 2 to 47892
Data columns (total 65 columns):
match_id              47391 non-null object
ElapsedTime           47391 non-null object
SetNo                 47391 non-null int64
P1GamesWon            47391 non-null int64
P2GamesWon            47391 non-null int64
SetWinner             47391 non-null int64
GameNo                47391 non-null int64
GameWinner            47391 non-null int64
PointNumber           47391 non-null object
PointWinner           47391 non-null int64
PointServer           47391 non-null int64
Speed_KMH             47391 non-null int64
Rally                 0 non-null float64
P1Score               47391 non-null object
P2Score               47391 non-null object
P1Momentum            47391 non-null int64
P2Momentum            47391 non-null int64
P1PointsWon           47391 non-null int64
P2PointsWon           47391 non-null int64
P1Ace                 47391 non-null int64
P2Ace                 47391 non-null int64
P1Winner              47391 non-null int64
P2Winner              47391 non-null int64
P1DoubleFault         47391 non-null int64
P2DoubleFault         47391 non-null int64
P1UnfErr              47391 non-null int64
P2UnfErr              47391 non-null int64
P1NetPoint            47391 non-null int64
P2NetPoint            47391 non-null int64
P1NetPointWon         47391 non-null int64
P2NetPointWon         47391 non-null int64
P1BreakPoint          47391 non-null int64
P2BreakPoint          47391 non-null int64
P1BreakPointWon       47391 non-null int64
P2BreakPointWon       47391 non-null int64
P1FirstSrvIn          0 non-null float64
P2FirstSrvIn          0 non-null float64
P1FirstSrvWon         0 non-null float64
P2FirstSrvWon         0 non-null float64
P1SecondSrvIn         0 non-null float64
P2SecondSrvIn         0 non-null float64
P1SecondSrvWon        0 non-null float64
P2SecondSrvWon        0 non-null float64
P1ForcedError         0 non-null float64
P2ForcedError         0 non-null float64
History               47391 non-null float64
Speed_MPH             47391 non-null int64
P1BreakPointMissed    47391 non-null int64
P2BreakPointMissed    47391 non-null int64
ServeIndicator        47391 non-null int64
Serve_Direction       0 non-null float64
Winner_FH             0 non-null float64
Winner_BH             0 non-null float64
ServingTo             0 non-null float64
P1TurningPoint        0 non-null float64
P2TurningPoint        0 non-null float64
ServeNumber           47391 non-null int64
WinnerType            47391 non-null object
WinnerShotType        47391 non-null object
P1DistanceRun         47391 non-null float64
P2DistanceRun         47391 non-null float64
RallyCount            47391 non-null int64
ServeWidth            25970 non-null object
ServeDepth            25970 non-null object
ReturnDepth           21183 non-null object
dtypes: float64(20), int64(35), object(10)
memory usage: 23.9+ MB

In [69]:
cols_to_drop = ['Serve_Direction','Winner_FH','Winner_BH','ServingTo',
                'P1TurningPoint','P2TurningPoint','P1FirstSrvIn',
                'P2FirstSrvIn','P1FirstSrvWon','P2FirstSrvWon',
               'P1SecondSrvIn','P2SecondSrvIn','P1SecondSrvWon',
               'P2SecondSrvWon','P1ForcedError','P2ForcedError',
               'Rally']

In [70]:
for col in cols_to_drop:
    pts_2019_usopen = pts_2019_usopen.drop(col, axis=1)

In [71]:
pts_2019_usopen.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47391 entries, 2 to 47892
Data columns (total 48 columns):
match_id              47391 non-null object
ElapsedTime           47391 non-null object
SetNo                 47391 non-null int64
P1GamesWon            47391 non-null int64
P2GamesWon            47391 non-null int64
SetWinner             47391 non-null int64
GameNo                47391 non-null int64
GameWinner            47391 non-null int64
PointNumber           47391 non-null object
PointWinner           47391 non-null int64
PointServer           47391 non-null int64
Speed_KMH             47391 non-null int64
P1Score               47391 non-null object
P2Score               47391 non-null object
P1Momentum            47391 non-null int64
P2Momentum            47391 non-null int64
P1PointsWon           47391 non-null int64
P2PointsWon           47391 non-null int64
P1Ace                 47391 non-null int64
P2Ace                 47391 non-null int64
P1Winner              47391 non-null int64
P2Winner              47391 non-null int64
P1DoubleFault         47391 non-null int64
P2DoubleFault         47391 non-null int64
P1UnfErr              47391 non-null int64
P2UnfErr              47391 non-null int64
P1NetPoint            47391 non-null int64
P2NetPoint            47391 non-null int64
P1NetPointWon         47391 non-null int64
P2NetPointWon         47391 non-null int64
P1BreakPoint          47391 non-null int64
P2BreakPoint          47391 non-null int64
P1BreakPointWon       47391 non-null int64
P2BreakPointWon       47391 non-null int64
History               47391 non-null float64
Speed_MPH             47391 non-null int64
P1BreakPointMissed    47391 non-null int64
P2BreakPointMissed    47391 non-null int64
ServeIndicator        47391 non-null int64
ServeNumber           47391 non-null int64
WinnerType            47391 non-null object
WinnerShotType        47391 non-null object
P1DistanceRun         47391 non-null float64
P2DistanceRun         47391 non-null float64
RallyCount            47391 non-null int64
ServeWidth            25970 non-null object
ServeDepth            25970 non-null object
ReturnDepth           21183 non-null object
dtypes: float64(3), int64(35), object(10)
memory usage: 17.7+ MB

In [200]:
pts_2019_usopen.ServeWidth.value_counts()

C     6956
W     5855
BW    5333
BC    4931
B     2895
Name: ServeWidth, dtype: int64

In [75]:
p1df = len(pts_2019_usopen[pts_2019_usopen['P1DoubleFault']==1])
p2df = len(pts_2019_usopen[pts_2019_usopen['P2DoubleFault']==1])

In [76]:
p1df + p2df

2286

In [78]:
pts_2019_usopen['ServeWidth'].isna().value_counts()

False    25970
True     21421
Name: ServeWidth, dtype: int64

In [83]:
pts_2019_usopen[pts_2019_usopen['ServeWidth'].isna()==True]

,match_id,ElapsedTime,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointNumber,PointWinner,...,ServeIndicator,ServeNumber,WinnerType,WinnerShotType,P1DistanceRun,P2DistanceRun,RallyCount,ServeWidth,ServeDepth,ReturnDepth
3,2019-usopen-1101,0:00:55,1,0,0,0,1,0,2,2,...,1,0,0,0,0.577,0.510,0,NaN,NaN,NaN
38,2019-usopen-1101,0:22:30,1,3,2,0,5,1,37,1,...,2,1,0,0,0.000,0.000,1,NaN,NaN,ND
50,2019-usopen-1101,0:32:46,1,4,3,0,8,0,49,1,...,2,1,0,0,0.000,0.000,4,NaN,NaN,NaN
97,2019-usopen-1101,1:06:55,2,4,1,0,6,0,96,1,...,2,0,0,0,0.294,0.247,0,NaN,NaN,NaN
108,2019-usopen-1101,1:15:20,3,0,0,0,1,0,107,2,...,2,2,0,0,0.000,0.000,1,NaN,NaN,D
117,2019-usopen-1101,1:20:42,3,0,1,0,2,0,116,2,...,1,0,0,0,0.459,0.535,0,NaN,NaN,NaN
156,2019-usopen-1101,1:46:22,3,5,3,0,9,0,155,1,...,2,0,0,0,0.594,0.457,0,NaN,NaN,NaN
168,2019-usopen-1102,0:00:00,1,0,0,0,1,0,1,2,...,1,0,0,0,0.000,0.000,0,NaN,NaN,NaN
188,2019-usopen-1102,0:09:31,1,2,2,0,5,0,21,2,...,1,0,0,0,0.000,0.000,0,NaN,NaN,NaN
197,2019-usopen-1102,0:15:10,1,4,2,0,6,1,30,1,...,1,0,0,0,0.530,0.513,0,NaN,NaN,NaN
294,2019-usopen-1102,1:12:40,3,3,3,0,7,0,127,2,...,1,0,0,0,0.000,0.000,0,NaN,NaN,NaN
347,2019-usopen-1102,1:46:43,4,0,1,0,2,0,180,2,...,1,0,0,0,0.466,0.555,0,NaN,NaN,NaN
360,2019-usopen-1102,1:53:58,4,2,2,0,5,0,193,1,...,2,0,0,0,0.538,0.714,0,NaN,NaN,NaN
404,2019-usopen-1103,0:00:00,1,0,0,0,1,0,1,2,...,2,1,0,0,0.000,0.000,1,NaN,NaN,NaN
405,2019-usopen-1103,0:00:32,1,0,0,0,1,0,2,2,...,2,2,0,0,0.000,0.000,3,NaN,NaN,NaN
406,2019-usopen-1103,0:00:52,1,0,0,0,1,0,3,2,...,2,1,0,0,0.000,0.000,1,NaN,NaN,NaN
407,2019-usopen-1103,0:01:17,1,0,0,0,1,0,4,1,...,2,2,0,0,0.000,0.000,2,NaN,NaN,NaN
408,2019-usopen-1103,0:01:47,1,0,1,0,1,2,5,2,...,1,1,0,0,0.000,0.000,1,NaN,NaN,NaN
409,2019-usopen-1103,0:02:37,1,0,1,0,2,0,6,2,...,1,0,0,0,0.000,0.000,0,NaN,NaN,NaN
410,2019-usopen-1103,0:03:00,1,0,1,0,2,0,7,1,...,1,1,0,0,0.000,0.000,1,NaN,NaN,NaN
411,2019-usopen-1103,0:03:22,1,0,1,0,2,0,8,2,...,1,2,0,0,0.000,0.000,2,NaN,NaN,NaN
412,2019-usopen-1103,0:03:52,1,0,1,0,2,0,9,1,...,1,1,0,0,0.000,0.000,1,NaN,NaN,NaN
413,2019-usopen-1103,0:04:21,1,0,1,0,2,0,10,2,...,1,2,0,0,0.000,0.000,2,NaN,NaN,NaN
414,2019-usopen-1103,0:05:10,1,0,1,0,2,0,11,1,...,1,1,0,0,0.000,0.000,3,NaN,NaN,NaN
415,2019-usopen-1103,0:06:03,1,0,1,0,2,0,12,2,...,1,2,0,0,0.000,0.000,2,NaN,NaN,NaN
416,2019-usopen-1103,0:06:45,1,0,2,0,2,2,13,2,...,2,2,0,0,0.000,0.000,2,NaN,NaN,NaN
417,2019-usopen-1103,0:07:25,1,0,2,0,3,0,14,2,...,2,1,0,0,0.000,0.000,3,NaN,NaN,NaN
418,2019-usopen-1103,0:07:52,1,0,2,0,3,0,15,2,...,2,1,0,0,0.000,0.000,1,NaN,NaN,NaN
419,2019-usopen-1103,0:08:20,1,0,2,0,3,0,16,1,...,2,0,0,0,0.000,0.000,0,NaN,NaN,NaN
420,2019-usopen-1103,0:08:46,1,0,2,0,3,0,17,1,...,2,1,0,0,0.000,0.000,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46207,2019-usopen-2403,1:11:42,2,6,4,1,10,1,108,1,...,1,0,0,0,0.317,0.489,0,NaN,NaN,NaN
46331,2019-usopen-2404,0:51:48,2,1,2,0,4,0,66,1,...,2,0,0,0,0.641,0.563,0,NaN,NaN,NaN
46435,2019-usopen-2405,0:47:21,2,1,1,0,3,0,81,1,...,2,0,0,0,0.394,0.530,0,NaN,NaN,NaN
46484,2019-usopen-2406,0:00:53,1,0,0,0,1,0,3,1,...,2,0,0,0,0.421,0.341,0,NaN,NaN,NaN
46509,2019-usopen-2406,0:17:43,1,3,1,0,5,0,28,1,...,2,0,0,0,0.423,0.533,0,NaN,NaN,NaN
46516,2019-usopen-2406,0:20:41,1,3,1,0,5,0,35,1,...,2,0,0,0,0.664,0.599,0,NaN,NaN,NaN
46575,2019-usopen-2406,1:05:19,2,0,1,0,2,0,94,1,...,2,0,0,0,0.540,0.496,0,NaN,NaN,NaN
46624,2019-usopen-2406,1:40:27,3,0,1,0,2,0,143,2,...,1,1,0,0,0.000,0.000,2,NaN,NaN,NaN
46627,2019-usopen-2406,1:42:14,3,1,1,0,3,0,146,2,...,2,1,0,F,0.000,0.000,3,NaN,NaN,NaN
46639,2019-usopen-2406,1:50:43,3,2,2,0,5,0,158,1,...,2,0,0,0,0.619,0.551,0,NaN,NaN,NaN
46708,2019-usopen-2407,0:15:21,1,2,1,0,4,0,25,2,...,2,1,0,0,0.000,0.000,1,NaN,NaN,D
46743,2019-usopen-2407,0:39:08,1,5,3,0,9,0,60,2,...,1,0,0,0,0.221,0.087,0,NaN,NaN,NaN
46779,2019-usopen-2407,1:10:35,2,3,2,0,6,0,96,2,...,1,0,0,0,0.480,0.276,0,NaN,NaN,NaN
46841,2019-usopen-2408,0:16:53,1,3,1,0,5,0,27,1,...,2,0,0,0,0.287,0.504,0,NaN,NaN,NaN
47033,2019-usopen-2501,1:07:19,2,0,1,0,2,0,94,2,...,1,0,0,0,0.731,0.507,0,NaN,NaN,NaN
47035,2019-usopen-2501,1:08:57,2,0,1,0,2,0,96,2,...,1,0,0,0,0.789,0.484,0,NaN,NaN,NaN
47150,2019-usopen-2502,0:47:32,2,1,0,0,2,0,66,1,...,2,0,0,0,0.233,0.383,0,NaN,NaN,NaN
47180,2019-usopen-2502,1:11:39,2,5,2,0,8,0,96,1,...,2,0,0,0,0.363,0.592,0,NaN,NaN,NaN
47398,2019-usopen-2504,0:08:03,1,2,0,0,3,0,16,2,...,1,0,0,0,0.729,0.348,0,NaN,NaN,NaN
47402,2019-usopen-2504,0:11:49,1,3,0,0,4,0,20,1,...,2,0,0,0,0.713,0.743,0,NaN,NaN,NaN
47465,2019-usopen-2601,0:09:27,1,2,1,0,4,0,16,1,...,2,0,0,0,0.610,0.522,0,NaN,NaN,NaN
47539,2019-usopen-2601,0:59:59,1,6,6,0,12,2,90,2,...,1,1,0,0,0.000,0.000,1,NaN,NaN,NaN
47551,2019-usopen-2601,1:11:32,2,0,0,0,1,0,102,1,...,2,0,0,0,0.463,0.581,0,NaN,NaN,NaN
47588,2019-usopen-2601,1:40:01,2,4,1,0,6,0,139,2,...,1,0,0,0,0.609,0.315,0,NaN,NaN,NaN
47616,2019-usopen-2601,2:00:18,2,5,5,0,11,0,167,1,...,2,0,0,0,0.393,0.569,0,NaN,NaN,NaN
47717,2019-usopen-2602,0:50:07,2,1,1,0,3,0,82,1,...,1,1,0,0,9.783,10.597,5,NaN,NaN,ND
47755,2019-usopen-2701,0:04:09,1,1,0,0,1,1,8,1,...,1,0,0,0,0.584,0.733,0,NaN,NaN,NaN
47810,2019-usopen-2701,0:39:42,1,5,3,0,9,0,63,1,...,2,2,0,B,0.000,0.000,6,NaN,NaN,D
47814,2019-usopen-2701,0:42:14,1,6,3,1,9,1,67,1,...,1,0,0,0,0.447,0.780,0,NaN,NaN,NaN
47853,2019-usopen-2701,1:11:07,2,4,1,0,6,0,106,1,...,2,0,0,0,0.274,0.691,0,NaN,NaN,NaN

In [84]:
pts_2019_usopen.head()

,match_id,ElapsedTime,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointNumber,PointWinner,...,ServeIndicator,ServeNumber,WinnerType,WinnerShotType,P1DistanceRun,P2DistanceRun,RallyCount,ServeWidth,ServeDepth,ReturnDepth
2,2019-usopen-1101,0:00:00,1,0,0,0,1,0,1,1,...,1,2,0,0,29.095,33.480,9,BC,NCTL,D
3,2019-usopen-1101,0:00:55,1,0,0,0,1,0,2,2,...,1,0,0,0,0.577,0.510,0,NaN,NaN,NaN
4,2019-usopen-1101,0:01:22,1,0,0,0,1,0,3,1,...,1,1,0,0,14.642,8.791,5,C,NCTL,ND
5,2019-usopen-1101,0:01:46,1,0,0,0,1,0,4,2,...,1,1,0,0,8.739,13.514,6,C,NCTL,ND
6,2019-usopen-1101,0:02:14,1,0,0,0,1,0,5,1,...,1,2,0,F,5.314,9.403,3,W,CTL,ND

In [85]:
pts_2019_usopen.ServeIndicator.value_counts()

1    23822
2    23569
Name: ServeIndicator, dtype: int64

In [138]:
np.array(pts_2019_usopen.match_id)[0].split('-')[2]

'1101'

In [151]:
#create unique id based on point number AND match id
pts_2019_usopen['match_id_simplified'] = [str(i.split('-')[2]) for i in np.array(pts_2019_usopen.match_id)]
type(pts_2019_usopen.match_id_simplified)
pts_2019_usopen['unique_id'] = np.array(pts_2019_usopen.match_id_simplified.values)+"-"+np.array(pts_2019_usopen.PointNumber.values)

In [154]:
pts_2019_usopen[0:10]

,match_id,ElapsedTime,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointNumber,PointWinner,...,WinnerType,WinnerShotType,P1DistanceRun,P2DistanceRun,RallyCount,ServeWidth,ServeDepth,ReturnDepth,unique_id,match_id_simplified
2,2019-usopen-1101,0:00:00,1,0,0,0,1,0,1,1,...,0,0,29.095,33.480,9,BC,NCTL,D,1101-1,1101
3,2019-usopen-1101,0:00:55,1,0,0,0,1,0,2,2,...,0,0,0.577,0.510,0,NaN,NaN,NaN,1101-2,1101
4,2019-usopen-1101,0:01:22,1,0,0,0,1,0,3,1,...,0,0,14.642,8.791,5,C,NCTL,ND,1101-3,1101
5,2019-usopen-1101,0:01:46,1,0,0,0,1,0,4,2,...,0,0,8.739,13.514,6,C,NCTL,ND,1101-4,1101
6,2019-usopen-1101,0:02:14,1,0,0,0,1,0,5,1,...,0,F,5.314,9.403,3,W,CTL,ND,1101-5,1101
7,2019-usopen-1101,0:02:47,1,1,0,0,1,1,6,1,...,0,F,8.286,8.471,3,C,NCTL,ND,1101-6,1101
8,2019-usopen-1101,0:03:38,1,1,0,0,2,0,7,2,...,0,0,2.570,2.205,1,BW,NCTL,NaN,1101-7,1101
9,2019-usopen-1101,0:03:58,1,1,0,0,2,0,8,1,...,0,0,4.383,5.058,2,BW,NCTL,D,1101-8,1101
10,2019-usopen-1101,0:04:20,1,1,0,0,2,0,9,1,...,0,F,47.075,56.260,18,BC,NCTL,ND,1101-9,1101
11,2019-usopen-1101,0:05:22,1,1,0,0,2,0,10,1,...,0,0,11.079,12.650,4,B,NCTL,D,1101-10,1101

In [153]:
pts_2019_usopen.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47391 entries, 2 to 47892
Data columns (total 50 columns):
match_id               47391 non-null object
ElapsedTime            47391 non-null object
SetNo                  47391 non-null int64
P1GamesWon             47391 non-null int64
P2GamesWon             47391 non-null int64
SetWinner              47391 non-null int64
GameNo                 47391 non-null int64
GameWinner             47391 non-null int64
PointNumber            47391 non-null object
PointWinner            47391 non-null int64
PointServer            47391 non-null int64
Speed_KMH              47391 non-null int64
P1Score                47391 non-null object
P2Score                47391 non-null object
P1Momentum             47391 non-null int64
P2Momentum             47391 non-null int64
P1PointsWon            47391 non-null int64
P2PointsWon            47391 non-null int64
P1Ace                  47391 non-null int64
P2Ace                  47391 non-null int64
P1Winner               47391 non-null int64
P2Winner               47391 non-null int64
P1DoubleFault          47391 non-null int64
P2DoubleFault          47391 non-null int64
P1UnfErr               47391 non-null int64
P2UnfErr               47391 non-null int64
P1NetPoint             47391 non-null int64
P2NetPoint             47391 non-null int64
P1NetPointWon          47391 non-null int64
P2NetPointWon          47391 non-null int64
P1BreakPoint           47391 non-null int64
P2BreakPoint           47391 non-null int64
P1BreakPointWon        47391 non-null int64
P2BreakPointWon        47391 non-null int64
History                47391 non-null float64
Speed_MPH              47391 non-null int64
P1BreakPointMissed     47391 non-null int64
P2BreakPointMissed     47391 non-null int64
ServeIndicator         47391 non-null int64
ServeNumber            47391 non-null int64
WinnerType             47391 non-null object
WinnerShotType         47391 non-null object
P1DistanceRun          47391 non-null float64
P2DistanceRun          47391 non-null float64
RallyCount             47391 non-null int64
ServeWidth             25970 non-null object
ServeDepth             25970 non-null object
ReturnDepth            21183 non-null object
unique_id              47391 non-null object
match_id_simplified    47391 non-null object
dtypes: float64(3), int64(35), object(12)
memory usage: 19.7+ MB

In [253]:
pts_2019_usopen.WinnerType.value_counts()

0    46646
S      745
Name: WinnerType, dtype: int64

In [255]:
sum(pts_2019_usopen['P1Ace'])+sum(pts_2019_usopen['P2Ace'])

3165

In [256]:
pts_2019_usopen.WinnerShotType.value_counts()

0    36135
F     7590
B     3666
Name: WinnerShotType, dtype: int64

In [207]:
len(pts_2019_usopen[(pts_2019_usopen['RallyCount']==1) | (pts_2019_usopen['RallyCount']==0)])

14508

In [235]:
len(pts_2019_usopen[(pts_2019_usopen['RallyCount']>1) & 
                (pts_2019_usopen['ServeWidth'].isna() == True)])

14640

In [252]:
pts_2019_usopen['match_id_simplified'].value_counts()

1204    398
1226    385
1143    383
1123    372
1122    358
1128    357
1311    357
1224    357
1134    351
1108    347
1133    344
1145    343
1701    341
1142    336
1129    327
1155    326
1110    326
1503    324
1310    321
1156    320
1106    313
1162    311
1313    303
1147    296
1304    294
1112    293
1231    292
1135    290
1315    289
1214    285
       ...
2602    110
2156    108
2313    108
2108    107
2107    106
2143    106
2154    106
2140    104
2116    103
2201    103
2144    103
2311    102
2308    102
2150    101
2224    100
2129     99
2215     96
2301     91
2404     87
2134     87
2149     84
2161     83
2309     83
2105     81
2221     80
2155     76
2104     75
1132     68
2504     65
1217     52
Name: match_id_simplified, Length: 251, dtype: int64

In [251]:
pts_2019_usopen[(pts_2019_usopen['RallyCount']>1) & 
                (pts_2019_usopen['ServeWidth'].isna() == True)]['match_id_simplified'].value_counts()>1

1204     True
1134     True
1110     True
1122     True
1226     True
1112     True
1143     True
1142     True
1106     True
1121     True
1210     True
1128     True
1224     True
1140     True
1163     True
1147     True
1156     True
1129     True
1214     True
1159     True
1130     True
1207     True
2152     True
1135     True
1126     True
1103     True
1202     True
2138     True
1211     True
1219     True
        ...
1312    False
2101    False
1311    False
2132    False
2221    False
2231    False
1408    False
1306    False
2311    False
2303    False
2216    False
1303    False
2701    False
1315    False
1222    False
1601    False
1132    False
1157    False
2602    False
2301    False
2312    False
2164    False
2204    False
2307    False
1101    False
2224    False
1502    False
1144    False
1313    False
1501    False
Name: match_id_simplified, Length: 216, dtype: bool

In [246]:
pts_2019_usopen[(pts_2019_usopen['RallyCount']>1) & 
                (pts_2019_usopen['ServeWidth'].isna() == True) 
                & (pts_2019_usopen['match_id_simplified']=='1219')][['match_id_simplified','unique_id',
                                                                 'PointNumber','PointWinner','PointServer',
                                                                'P1DoubleFault','P2DoubleFault','P1Ace',
                                                                'P2Ace','WinnerType','WinnerShotType',
                                                                'ServeWidth','ServeDepth','ReturnDepth']]

,match_id_simplified,unique_id,PointNumber,PointWinner,PointServer,P1DoubleFault,P2DoubleFault,P1Ace,P2Ace,WinnerType,WinnerShotType,ServeWidth,ServeDepth,ReturnDepth
19610,1219,1219-1,1,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19611,1219,1219-2,2,1,2,0,0,0,0,0,F,NaN,NaN,NaN
19612,1219,1219-3,3,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19613,1219,1219-4,4,2,2,0,0,0,0,0,B,NaN,NaN,NaN
19614,1219,1219-5,5,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19615,1219,1219-6,6,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19618,1219,1219-9,9,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19620,1219,1219-11,11,1,1,0,0,0,0,0,F,NaN,NaN,NaN
19621,1219,1219-12,12,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19623,1219,1219-14,14,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19624,1219,1219-15,15,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19625,1219,1219-16,16,1,1,0,0,0,0,0,0,NaN,NaN,NaN
19626,1219,1219-17,17,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19627,1219,1219-18,18,1,1,0,0,0,0,0,F,NaN,NaN,NaN
19628,1219,1219-19,19,1,1,0,0,0,0,0,F,NaN,NaN,NaN
19632,1219,1219-23,23,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19633,1219,1219-24,24,2,2,0,0,0,0,0,B,NaN,NaN,NaN
19636,1219,1219-27,27,1,1,0,0,0,0,0,0,NaN,NaN,NaN
19637,1219,1219-28,28,1,1,0,0,0,0,0,F,NaN,NaN,NaN
19638,1219,1219-29,29,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19639,1219,1219-30,30,2,1,0,0,0,0,0,F,NaN,NaN,NaN
19640,1219,1219-31,31,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19641,1219,1219-32,32,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19643,1219,1219-34,34,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19644,1219,1219-35,35,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19645,1219,1219-36,36,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19646,1219,1219-37,37,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19648,1219,1219-39,39,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19652,1219,1219-43,43,2,1,0,0,0,0,0,B,NaN,NaN,NaN
19653,1219,1219-44,44,1,1,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19812,1219,1219-203,203,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19813,1219,1219-204,204,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19814,1219,1219-205,205,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19815,1219,1219-206,206,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19816,1219,1219-207,207,2,2,0,0,0,0,0,B,NaN,NaN,NaN
19821,1219,1219-212,212,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19822,1219,1219-213,213,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19823,1219,1219-214,214,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19824,1219,1219-215,215,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19825,1219,1219-216,216,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19826,1219,1219-217,217,1,1,0,0,0,0,0,B,NaN,NaN,NaN
19827,1219,1219-218,218,1,1,0,0,0,0,0,0,NaN,NaN,NaN
19828,1219,1219-219,219,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19831,1219,1219-222,222,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19832,1219,1219-223,223,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19833,1219,1219-224,224,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19835,1219,1219-226,226,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19836,1219,1219-227,227,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19837,1219,1219-228,228,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19839,1219,1219-230,230,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19840,1219,1219-231,231,1,2,0,0,0,0,0,B,NaN,NaN,NaN
19841,1219,1219-232,232,2,1,0,0,0,0,0,0,NaN,NaN,NaN
19845,1219,1219-236,236,1,1,0,0,0,0,0,F,NaN,NaN,NaN
19846,1219,1219-237,237,1,2,0,0,0,0,0,F,NaN,NaN,NaN
19847,1219,1219-238,238,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19848,1219,1219-239,239,2,2,0,0,0,0,0,B,NaN,NaN,NaN
19849,1219,1219-240,240,2,2,0,0,0,0,0,0,NaN,NaN,NaN
19850,1219,1219-241,241,2,2,0,0,0,0,0,F,NaN,NaN,NaN
19851,1219,1219-242,242,1,2,0,0,0,0,0,0,NaN,NaN,NaN
19856,1219,1219-247,247,1,1,0,0,0,0,0,0,NaN,NaN,NaN

In [229]:
pts_2019_usopen.ReturnDepth.isna()

2        False
3         True
4        False
5        False
6        False
7        False
8         True
9        False
10       False
11       False
12        True
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21        True
22       False
23       False
24       False
25       False
26       False
27        True
28       False
29       False
30       False
31       False
         ...
47863    False
47864    False
47865    False
47866    False
47867     True
47868    False
47869    False
47870    False
47871    False
47872    False
47873    False
47874    False
47875     True
47876     True
47877     True
47878     True
47879    False
47880    False
47881     True
47882     True
47883     True
47884     True
47885    False
47886    False
47887    False
47888    False
47889    False
47890    False
47891     True
47892    False
Name: ReturnDepth, Length: 47391, dtype: bool

In [157]:
pts_2019_usopen.P1Score[0:5]

2    15
3    15
4    30
5    30
6    40
Name: P1Score, dtype: object

In [159]:
pts_2019_usopen.P1PointsWon[0:5]

2    1
3    1
4    2
5    2
6    3
Name: P1PointsWon, dtype: int64

In [160]:
pts_2019_usopen.P1Momentum[0:5]

2    2
3    1
4    3
5    1
6    4
Name: P1Momentum, dtype: int64

In [176]:
pts_2019_usopen[['unique_id','GameNo','P1PointsWon',
                 'P2PointsWon','P1Winner','P2Winner',
                'P1NetPoint','P2NetPoint',
                'P1NetPointWon','P2NetPointWon','P1BreakPoint','P2BreakPoint',
                'P1BreakPointWon','P2BreakPointWon',
                 'P1BreakPointMissed','P2BreakPointMissed',
                 'ServeIndicator','ServeNumber','WinnerType','WinnerShotType']][0:50]

,unique_id,GameNo,P1PointsWon,P2PointsWon,P1Winner,P2Winner,P1NetPoint,P2NetPoint,P1NetPointWon,P2NetPointWon,P1BreakPoint,P2BreakPoint,P1BreakPointWon,P2BreakPointWon,P1BreakPointMissed,P2BreakPointMissed,ServeIndicator,ServeNumber,WinnerType,WinnerShotType
2,1101-1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0
3,1101-2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,1101-3,1,2,1,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0
5,1101-4,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
6,1101-5,1,3,2,1,0,0,0,0,0,0,0,0,0,0,0,1,2,0,F
7,1101-6,1,4,2,1,0,1,0,1,0,0,0,0,0,0,0,2,1,0,F
8,1101-7,2,4,3,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
9,1101-8,2,5,3,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
10,1101-9,2,6,3,1,0,1,0,1,0,0,0,0,0,0,0,2,2,0,F
11,1101-10,2,7,3,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
12,1101-11,2,7,4,0,1,0,0,0,0,1,0,0,0,1,0,2,1,0,0
13,1101-12,2,7,5,0,0,0,0,0,0,1,0,0,0,1,0,2,1,0,0
14,1101-13,2,7,6,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
15,1101-14,2,8,6,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
16,1101-15,2,8,7,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
17,1101-16,2,9,7,0,0,1,0,1,0,0,0,0,0,0,0,2,1,0,0
18,1101-17,2,10,7,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
19,1101-18,2,10,8,0,1,0,0,0,0,1,0,0,0,1,0,2,1,0,B
20,1101-19,2,10,9,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
21,1101-20,2,11,9,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0
22,1101-21,2,11,10,0,1,0,0,0,0,0,0,0,0,0,0,2,1,0,B
23,1101-22,2,11,11,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
24,1101-23,3,12,11,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,F
25,1101-24,3,13,11,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
26,1101-25,3,14,11,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
27,1101-26,3,15,11,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
28,1101-27,4,16,11,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
29,1101-28,4,16,12,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
30,1101-29,4,16,13,0,1,0,0,0,0,0,0,0,0,0,0,2,1,0,B
31,1101-30,4,16,14,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
32,1101-31,4,16,15,0,1,0,1,0,1,0,0,0,0,0,0,1,1,0,F
33,1101-32,5,17,15,1,0,1,0,1,0,0,0,0,0,0,0,1,1,0,F
34,1101-33,5,18,15,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
35,1101-34,5,18,16,0,1,0,0,0,0,0,0,0,0,0,0,1,2,0,B
36,1101-35,5,18,17,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
37,1101-36,5,19,17,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
38,1101-37,5,20,17,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
39,1101-38,6,20,18,0,0,0,1,0,1,0,0,0,0,0,0,2,2,0,0
40,1101-39,6,21,18,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
41,1101-40,6,21,19,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
42,1101-41,6,21,20,0,1,0,1,0,1,0,0,0,0,0,0,2,1,0,F
43,1101-42,6,21,21,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0
44,1101-43,7,22,21,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0
45,1101-44,7,23,21,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
46,1101-45,7,23,22,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0
47,1101-46,7,23,23,0,1,0,0,0,0,0,0,0,0,0,0,1,2,0,B
48,1101-47,7,24,23,1,0,1,0,1,0,0,0,0,0,0,0,1,1,0,F
49,1101-48,7,25,23,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0
50,1101-49,8,26,23,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0
51,1101-50,8,26,24,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0

In [171]:
pts_2019_usopen.P1UnfErr.value_counts()

0    38651
1     8740
Name: P1UnfErr, dtype: int64

In [187]:
pts_2019_usopen[['SetNo','P1GamesWon','P2GamesWon',
                 'SetWinner','GameNo','GameWinner',
                 'PointWinner','PointNumber','P1PointsWon',
                 'P2PointsWon',]][-5:]

,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointWinner,PointNumber,P1PointsWon,P2PointsWon
47888,2,6,5,0,12,0,2,141,74,67
47889,2,6,5,0,12,0,1,142,75,67
47890,2,6,5,0,12,0,1,143,76,67
47891,2,6,5,0,12,0,2,144,76,68
47892,2,7,5,1,12,1,1,145,77,68

In [205]:
pts_2019_usopen[pts_2019_usopen['match_id_simplified']== '2701'][['SetNo','P1GamesWon','P2GamesWon',
                 'GameWinner','PointWinner','PointNumber','P1PointsWon',
                 'P2PointsWon','PointServer','P1DoubleFault','P2DoubleFault',
                                                                  'P1Ace','P2Ace',
                                                                  'P1UnfErr','P2UnfErr','RallyCount',
                                                                  'ServeWidth','ServeDepth','ReturnDepth']]

,SetNo,P1GamesWon,P2GamesWon,GameWinner,PointWinner,PointNumber,P1PointsWon,P2PointsWon,PointServer,P1DoubleFault,P2DoubleFault,P1Ace,P2Ace,P1UnfErr,P2UnfErr,RallyCount,ServeWidth,ServeDepth,ReturnDepth
47748,1,0,0,0,2,1,0,1,2,0,0,0,1,0,0,1,W,CTL,NaN
47749,1,0,0,0,1,2,1,1,2,0,0,0,0,0,1,4,BW,CTL,D
47750,1,0,0,0,2,3,1,2,2,0,0,0,0,0,0,1,W,CTL,D
47751,1,0,0,0,2,4,1,3,2,0,0,0,0,0,0,5,BW,CTL,ND
47752,1,0,0,0,1,5,2,3,2,0,0,0,0,0,1,4,B,NCTL,ND
47753,1,0,0,0,1,6,3,3,2,0,0,0,0,0,1,6,C,NCTL,D
47754,1,0,0,0,1,7,4,3,2,0,1,0,0,0,1,0,BC,CTL,NaN
47755,1,1,0,1,1,8,5,3,2,0,1,0,0,0,1,0,NaN,NaN,NaN
47756,1,1,0,0,2,9,5,4,1,0,0,0,0,0,0,2,BC,NCTL,D
47757,1,1,0,0,1,10,6,4,1,0,0,0,0,0,0,5,C,NCTL,D
47758,1,1,0,0,2,11,6,5,1,0,0,0,0,0,0,6,BW,CTL,D
47759,1,1,0,0,1,12,7,5,1,0,0,1,0,0,0,1,W,CTL,NaN
47760,1,1,0,0,1,13,8,5,1,0,0,0,0,0,0,1,C,NCTL,ND
47761,1,2,0,1,1,14,9,5,1,0,0,0,0,0,0,1,B,NCTL,NaN
47762,1,2,0,0,2,15,9,6,2,0,0,0,0,0,0,7,C,NCTL,D
47763,1,2,0,0,2,16,9,7,2,0,0,0,0,0,0,9,W,NCTL,ND
47764,1,2,0,0,2,17,9,8,2,0,0,0,0,0,0,1,C,CTL,NaN
47765,1,2,0,0,1,18,10,8,2,0,0,0,0,0,1,2,C,NCTL,ND
47766,1,2,1,2,2,19,10,9,2,0,0,0,0,0,0,3,W,NCTL,ND
47767,1,2,1,0,2,20,10,10,1,0,0,0,0,0,0,2,W,CTL,ND
47768,1,2,1,0,1,21,11,10,1,0,0,0,0,0,1,7,B,CTL,ND
47769,1,2,1,0,1,22,12,10,1,0,0,0,0,0,1,1,BC,NCTL,D
47770,1,2,1,0,1,23,13,10,1,0,0,0,0,0,1,3,BW,CTL,D
47771,1,3,1,1,1,24,14,10,1,0,0,0,0,0,0,1,W,CTL,ND
47772,1,3,1,0,2,25,14,11,2,0,0,0,0,0,0,5,BC,CTL,ND
47773,1,3,1,0,2,26,14,12,2,0,0,0,0,1,0,3,C,NCTL,D
47774,1,3,1,0,1,27,15,12,2,0,0,0,0,0,0,2,BC,NCTL,D
47775,1,3,1,0,2,28,15,13,2,0,0,0,1,0,0,1,C,NCTL,NaN
47776,1,3,2,2,2,29,15,14,2,0,0,0,0,0,0,1,BC,NCTL,D
47777,1,3,2,0,1,30,16,14,1,0,0,0,0,0,0,1,B,CTL,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47863,2,5,1,0,1,116,66,50,1,0,0,0,0,0,0,3,BC,NCTL,D
47864,2,5,1,0,2,117,66,51,1,0,0,0,0,0,0,12,B,NCTL,ND
47865,2,5,2,2,2,118,66,52,1,0,0,0,0,0,0,2,BC,NCTL,ND
47866,2,5,2,0,2,119,66,53,2,0,0,0,0,0,0,1,C,NCTL,ND
47867,2,5,2,0,2,120,66,54,2,0,0,0,1,0,0,1,C,NCTL,NaN
47868,2,5,2,0,2,121,66,55,2,0,0,0,0,0,0,5,BC,NCTL,ND
47869,2,5,2,0,1,122,67,55,2,0,0,0,0,0,1,4,C,NCTL,ND
47870,2,5,3,2,2,123,67,56,2,0,0,0,0,0,0,1,BW,NCTL,ND
47871,2,5,3,0,2,124,67,57,1,0,0,0,0,1,0,4,C,NCTL,D
47872,2,5,3,0,2,125,67,58,1,0,0,0,0,1,0,2,W,CTL,ND
47873,2,5,3,0,2,126,67,59,1,0,0,0,0,0,0,8,B,NCTL,D
47874,2,5,4,2,2,127,67,60,1,0,0,0,0,1,0,10,C,CTL,ND
47875,2,5,4,0,2,128,67,61,2,0,0,0,1,0,0,1,C,CTL,NaN
47876,2,5,4,0,1,129,68,61,2,0,1,0,0,0,1,0,BW,CTL,NaN
47877,2,5,4,0,2,130,68,62,2,0,0,0,1,0,0,1,C,CTL,NaN
47878,2,5,4,0,1,131,69,62,2,0,1,0,0,0,1,0,BC,CTL,NaN
47879,2,5,4,0,2,132,69,63,2,0,0,0,0,0,0,1,BC,CTL,ND
47880,2,5,5,2,2,133,69,64,2,0,0,0,0,1,0,1,B,NCTL,D
47881,2,5,5,0,1,134,70,64,1,0,0,0,0,0,0,1,C,NCTL,NaN
47882,2,5,5,0,2,135,70,65,1,1,0,0,0,1,0,0,W,CTL,NaN
47883,2,5,5,0,1,136,71,65,1,0,0,0,0,0,0,1,BC,NCTL,NaN
47884,2,5,5,0,1,137,72,65,1,0,0,1,0,0,0,1,C,NCTL,NaN
47885,2,5,5,0,2,138,72,66,1,0,0,0,0,1,0,2,B,NCTL,ND
47886,2,6,5,1,1,139,73,66,1,0,0,0,0,0,1,3,C,NCTL,ND
47887,2,6,5,0,1,140,74,66,2,0,0,0,0,0,1,6,BC,NCTL,D
47888,2,6,5,0,2,141,74,67,2,0,0,0,0,0,0,3,BW,NCTL,ND
47889,2,6,5,0,1,142,75,67,2,0,0,0,0,0,0,2,B,NCTL,ND
47890,2,6,5,0,1,143,76,67,2,0,0,0,0,0,1,6,BW,NCTL,ND
47891,2,6,5,0,2,144,76,68,2,0,0,0,1,0,0,1,W,CTL,NaN
47892,2,7,5,1,1,145,77,68,2,0,0,0,0,0,0,2,BW,NCTL,D

In [222]:
df_2701 = pts_2019_usopen[pts_2019_usopen['match_id_simplified']== '2701']

In [190]:
pts_2019_usopen.P1BreakPointWon.value_counts()

0    46412
1      979
Name: P1BreakPointWon, dtype: int64

In [197]:
pts_2019_usopen[pts_2019_usopen['match_id_simplified']== '2701'][['PointServer','WinnerType',
                                                                  'PointNumber','PointWinner',
                                                                  'RallyCount','P1Ace','P2Ace',
                                                                  'P1PointsWon','P2PointsWon',
                                                                 'P1Score','P2Score']][0:3]

,PointServer,WinnerType,PointNumber,PointWinner,RallyCount,P1Ace,P2Ace,P1PointsWon,P2PointsWon,P1Score,P2Score
47748,2,0,1,2,1,0,1,0,1,0,15
47749,2,0,2,1,4,0,0,1,1,15,15
47750,2,0,3,2,1,0,0,1,2,15,30

In [198]:
len(pts_2019_usopen[pts_2019_usopen['match_id_simplified']== '2701'])

145

In [257]:
m_2019_usopen = pd.read_csv('./data/2019-usopen-matches.csv')

In [261]:
m_2019_usopen[100:150]

,match_id,year,slam,match_num,player1,player2,status,winner,event_name,round,court_name,court_id,player1id,player2id,nation1,nation2
100,2019-usopen-1307,2019,usopen,1307,Grigor Dimitrov,Kamil Majchrzak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,2019-usopen-1308,2019,usopen,1308,Alex de Minaur,Kei Nishikori,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2019-usopen-1309,2019,usopen,1309,Andrey Rublev,Nick Kyrgios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,2019-usopen-1310,2019,usopen,1310,Matteo Berrettini,Alexei Popyrin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2019-usopen-1311,2019,usopen,1311,Gael Monfils,Denis Shapovalov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,2019-usopen-1312,2019,usopen,1312,Pablo Andujar,Alexander Bublik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,2019-usopen-1313,2019,usopen,1313,Alexander Zverev,Aljaz Bedene,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,2019-usopen-1314,2019,usopen,1314,Diego Schwartzman,Tennys Sandgren,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,2019-usopen-1315,2019,usopen,1315,John Isner,Marin Cilic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,2019-usopen-1316,2019,usopen,1316,Hyeon Chung,Rafael Nadal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,2019-usopen-1401,2019,usopen,1401,Novak Djokovic,Stan Wawrinka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,2019-usopen-1402,2019,usopen,1402,Dominik Koepfer,Daniil Medvedev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,2019-usopen-1403,2019,usopen,1403,Roger Federer,David Goffin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,2019-usopen-1404,2019,usopen,1404,Grigor Dimitrov,Alex de Minaur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,2019-usopen-1405,2019,usopen,1405,Andrey Rublev,Matteo Berrettini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,2019-usopen-1406,2019,usopen,1406,Gael Monfils,Pablo Andujar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,2019-usopen-1407,2019,usopen,1407,Alexander Zverev,Diego Schwartzman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2019-usopen-1408,2019,usopen,1408,Marin Cilic,Rafael Nadal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,2019-usopen-1501,2019,usopen,1501,Stan Wawrinka,Daniil Medvedev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2019-usopen-1502,2019,usopen,1502,Roger Federer,Grigor Dimitrov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,2019-usopen-1503,2019,usopen,1503,Matteo Berrettini,Gael Monfils,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,2019-usopen-1504,2019,usopen,1504,Diego Schwartzman,Rafael Nadal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,2019-usopen-1601,2019,usopen,1601,Daniil Medvedev,Grigor Dimitrov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,2019-usopen-1602,2019,usopen,1602,Matteo Berrettini,Rafael Nadal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,2019-usopen-1701,2019,usopen,1701,Daniil Medvedev,Rafael Nadal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,2019-usopen-2101,2019,usopen,2101,Naomi Osaka,Anna Blinkova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,2019-usopen-2102,2019,usopen,2102,Astra Sharma,Magda Linette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,2019-usopen-2103,2019,usopen,2103,Anastasia Potapova,Coco Gauff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,2019-usopen-2104,2019,usopen,2104,Timea Babos,Carla Suárez Navarro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,2019-usopen-2105,2019,usopen,2105,Anett Kontaveit,Sara Sorribes Tormo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,2019-usopen-2106,2019,usopen,2106,Ajla Tomljanovic,Marie Bouzkova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,2019-usopen-2107,2019,usopen,2107,Alizé Cornet,Jessica Pegula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,2019-usopen-2108,2019,usopen,2108,Mandy Minella,Belinda Bencic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,2019-usopen-2109,2019,usopen,2109,Aryna Sabalenka,Victoria Azarenka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,2019-usopen-2110,2019,usopen,2110,Yulia Putintseva,Madison Brengle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,2019-usopen-2111,2019,usopen,2111,Kaia Kanepi,Tatjana Maria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,2019-usopen-2112,2019,usopen,2112,Richel Hogenkamp,Donna Vekic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,2019-usopen-2113,2019,usopen,2113,Julia Goerges,Natalia Vikhlyantseva,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,2019-usopen-2114,2019,usopen,2114,Francesca Di Lorenzo,Veronika Kudermetova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,2019-usopen-2115,2019,usopen,2115,Pauline Parmentier,Anastasia Pavlyuchenkova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,2019-usopen-2116,2019,usopen,2116,Paula Badosa,Kiki Bertens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,2019-usopen-2117,2019,usopen,2117,Simona Halep,Nicole Gibbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,2019-usopen-2118,2019,usopen,2118,Taylor Townsend,Kateryna Kozlova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,2019-usopen-2119,2019,usopen,2119,Sorana Cirstea,Katerina Siniakova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,2019-usopen-2120,2019,usopen,2120,Aliona Bolsova,Barbora Strycova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,2019-usopen-2121,2019,usopen,2121,Caroline Wozniacki,Yafan Wang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,2019-usopen-2122,2019,usopen,2122,Danielle Collins,Polona Hercog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,2019-usopen-2123,2019,usopen,2123,Xiyu Wang,Kirsten Flipkens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,2019-usopen-2124,2019,usopen,2124,Katie Volynets,Bianca Andreescu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,2019-usopen-2125,2019,usopen,2125,Sloane Stephens,Anna Kalinskaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [259]:
m_2019_usopen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 16 columns):
match_id      251 non-null object
year          251 non-null int64
slam          251 non-null object
match_num     251 non-null int64
player1       251 non-null object
player2       251 non-null object
status        0 non-null float64
winner        0 non-null float64
event_name    0 non-null float64
round         0 non-null float64
court_name    0 non-null float64
court_id      0 non-null float64
player1id     0 non-null float64
player2id     0 non-null float64
nation1       0 non-null float64
nation2       0 non-null float64
dtypes: float64(10), int64(2), object(4)
memory usage: 31.5+ KB

In [262]:
pts_2019_usopen.P1Score[2]

'15'